import { scope } from "arktype";
import { binary } from "./binary";
import { $ as schema } from "./schema";
import type { ArkMeta } from "./core";

/**
 * Core schema definitions for the Linear Layout Plan (LLP).
 */
export const $layout = scope({
	...binary.import(),
	...schema.import(),

	/** Unified layout information for any element */
	TypeLayout: {
		"...": "Base",
		size: "number",
		align: "number",
		paddedSize: "number",
		name: "string",
	},

	/** Recursive field definition */
	Field:
		"PrimitiveField | ReferenceField | ArrayField | StringField | OptionalField | InlineStructField | UnitField | MapField | AnyField",

	PrimitiveField: {
		"...": "TypeLayout",
		name: "string",
		kind: "'primitive'",
	},

	/**
	 * Index-signature / Record<K, V>. No fixed memory layout; binary-tier
	 * exporters should skip these with a warning. `value` is recursive Field.
	 */
	MapField: {
		kind: "'map'",
		keyKind: "'string' | 'number' | 'symbol'",
		value: "Field",
	},

	/**
	 * arktype `unknown` / `any` / `unknown.any`. Carries no shape info;
	 * exporters that can render an opaque value (TS `unknown`, JSON `any`)
	 * may emit it; binary-tier exporters skip with a warning.
	 *
	 * Importers that fall back to `any` because they couldn't resolve a
	 * source type (e.g. clang_importer hitting `size_t` with no
	 * `<stddef.h>` available, or `const char *` which has no schema-pop
	 * equivalent) attach the original spelling on `originalType` so
	 * downstream tooling can recover the user's intent later — pop it
	 * back to a real type once we model that shape, drive a manual
	 * binding emit, render in HTML viewer, etc.
	 */
	AnyField: {
		kind: "'any'",
		name: "string",
		"originalType?": "string",
	},

	ReferenceField: {
		kind: "'reference'",
		name: "string",
		indirection: "'inline' | 'pointer' | 'reference'",
		isForward: "boolean",
	},

	ArrayField: {
		kind: "'array'",
		item: "Field",
		"maxLength?": "number",
		"exactLength?": "number",
	},

	StringField: {
		kind: "'string'",
		"maxLength?": "number",
		"exactLength?": "number",
	},

	OptionalField: {
		kind: "'optional'",
		inner: "Field",
	},

	UnitField: {
		kind: "'unit'",
	},

	/** A specific instance of a field within a structure */
	FieldPlan: {
		name: "string",
		type: "Field",
		offset: "number",
		bitOffset: "number<8",
		bitSize: "number",
		size: "number",
		paddingAfter: "number",
	},

	InlineStructField: {
		"...": "TypeLayout",
		kind: "'inlineStruct'",
		fields: "FieldPlan[]",
	},

	VariantPlan: {
		name: "string",
		type: "Field",
		"tag?": "number",
	},

	/** Top-level type definitions */
	StructPlan: {
		"...": "TypeLayout",
		name: "string",
		kind: "'struct'",
		fields: "FieldPlan[]",
		"description?": "string",
		"obsolete?": "boolean",
		"obsoleteReason?": "string",
	},

	UnionPlan: {
		"...": "TypeLayout",
		name: "string",
		kind: "'union'",
		tagOffset: "number",
		tagSize: "number",
		tagType: "'u8' | 'u16' | 'u32'",
		variants: "VariantPlan[]",
		"description?": "string",
		"obsolete?": "boolean",
		"obsoleteReason?": "string",
		discriminant: "string?",
	},

	EnumVariant: {
		name: "string",
		value: "number",
		description: "string?",
	},

	EnumPlan: {
		"...": "TypeLayout",
		name: "string",
		kind: "'enum'",
		variants: "EnumVariant[]",
		underlyingType: "'u8' | 'u16' | 'i32'",
		"description?": "string",
		"obsolete?": "boolean",
		"obsoleteReason?": "string",
		"syntetic?": "boolean", // Was this type generated by analyzer?
	},

	AliasPlan: {
		"...": "TypeLayout",
		name: "string",
		kind: "'alias'",
		type: "Field",
		"targetOffset?": "number", // Binary offset of the aliased type
		"description?": "string",
		"obsolete?": "boolean",
		"obsoleteReason?": "string",
	},

	/** A single WebGPU resource binding entry */
	GpuBinding: {
		name: "string",
		group: "number",
		binding: "number",
		usage: "string",
		dataTypeName: "string",
		isArray: "boolean",
	},

	GpuShader: {
		name: "string",
		bindGroups: "number[]",
		entryPoint: "string",
		workGroupSize: "number",
	},

	/** A struct where every field is a Binding<> — generates layout descriptors instead of binary struct */
	GpuBindingPlan: {
		"...": "TypeLayout",
		kind: "'gpu-binding-layout'",
		bindings: "GpuBinding[]",
		shaders: "GpuShader[]",
	},

	TypePlan: "StructPlan | UnionPlan | EnumPlan | AliasPlan | GpuBindingPlan",

	/** The complete Linear Layout Plan (LLP) */
	LayoutPlan: {
		"...": "PopSchemaSettings",
		types: "TypePlan[]",
	},
});

const layout = $layout.export();

export const {
	AliasPlan,
	AnyField,
	// ArrayField,
	EnumPlan,
	EnumVariant,
	Field,
	FieldPlan,
	GpuBinding,
	GpuBindingPlan,
	InlineStructField,
	MapField,
	OptionalField,
	PrimitiveField,
	ReferenceField,
	StringField,
	StructPlan,
	UnionPlan,
	VariantPlan,
	TypePlan,
	TypeLayout,
	LayoutPlan,
} = layout;



export type AliasPlan = typeof AliasPlan.infer & ArkMeta;
export type AnyField = typeof AnyField.infer & ArkMeta;
export type EnumPlan = typeof EnumPlan.infer & ArkMeta;
export type EnumVariant = typeof EnumVariant.infer & ArkMeta;
export type Field = typeof Field.infer & ArkMeta;
export type FieldPlan = typeof FieldPlan.infer & ArkMeta;
export type GpuBinding = typeof GpuBinding.infer & ArkMeta;
export type GpuBindingPlan = typeof GpuBindingPlan.infer & ArkMeta;
export type InlineStructField = typeof InlineStructField.infer & ArkMeta;
export type MapField = typeof MapField.infer & ArkMeta;
export type OptionalField = typeof OptionalField.infer & ArkMeta;
export type PrimitiveField = typeof PrimitiveField.infer & ArkMeta;
export type ReferenceField = typeof ReferenceField.infer & ArkMeta;
export type StringField = typeof StringField.infer & ArkMeta;
export type StructPlan = typeof StructPlan.infer & ArkMeta;
export type UnionPlan = typeof UnionPlan.infer & ArkMeta;
export type VariantPlan = typeof VariantPlan.infer & ArkMeta;
export type TypePlan = typeof TypePlan.infer & ArkMeta;
export type TypeLayout = typeof TypeLayout.infer & ArkMeta;
export type LayoutPlan = typeof LayoutPlan.infer & ArkMeta;

export const ArrayField = layout.ArrayField.omit("item").and({ item: Field });
export type ArrayField = typeof ArrayField.infer & ArkMeta;