import { scope } from "arktype";
import { binary } from "./binary";
import { $ as schema } from "./schema";

/**
 * Core schema definitions for the Linear Layout Plan (LLP).
 */
export const $layout = scope({
	...binary.import(),
	...schema.import(),

	/** Unified layout information for any element */
	TypeLayout: {
		size: "number",
		align: "number",
		paddedSize: "number",
	},

	/** Recursive field definition */
	Field:
		"PrimitiveField | ReferenceField | ArrayField | StringField | OptionalField | InlineStructField | UnitField | MapField | AnyField",

	PrimitiveField: {
		"...": "TypeLayout",
		kind: "'primitive'",
		name: "string",
		"bitSize?": "number",
		"unsigned?": "boolean",
		"isFloat?": "boolean",
		popKind: "'binary' | 'bitwise' | 'reserved' | 'rich' = 'binary'",
	},

	/**
	 * Index-signature / Record<K, V>. No fixed memory layout; binary-tier
	 * exporters should skip these with a warning. `value` is recursive Field.
	 */
	MapField: {
		kind: "'map'",
		keyKind: "'string' | 'number' | 'symbol' = 'string'",
		value: "Field",
	},

	/**
	 * arktype `unknown` / `any` / `unknown.any`. Carries no shape info;
	 * exporters that can render an opaque value (TS `unknown`, JSON `any`)
	 * may emit it; binary-tier exporters skip with a warning.
	 *
	 * Importers that fall back to `any` because they couldn't resolve a
	 * source type (e.g. clang_importer hitting `size_t` with no
	 * `<stddef.h>` available, or `const char *` which has no schema-pop
	 * equivalent) attach the original spelling on `originalType` so
	 * downstream tooling can recover the user's intent later — pop it
	 * back to a real type once we model that shape, drive a manual
	 * binding emit, render in HTML viewer, etc.
	 */
	AnyField: {
		kind: "'any'",
		"originalType?": "string",
	},

	ReferenceField: {
		kind: "'reference'",
		name: "string",
		indirection: "'inline' | 'pointer' | 'reference'",
		isForward: "boolean",
	},

	ArrayField: {
		kind: "'array'",
		item: "Field",
		"maxLength?": "number",
		"exactLength?": "number",
	},

	StringField: {
		kind: "'string'",
		"maxLength?": "number",
		"exactLength?": "number",
	},

	OptionalField: {
		kind: "'optional'",
		inner: "Field",
	},

	UnitField: {
		kind: "'unit'",
	},

	/** A specific instance of a field within a structure */
	FieldPlan: {
		name: "string",
		type: "Field",
		offset: "number",
		bitOffset: "number<8",
		bitSize: "number",
		size: "number",
		paddingAfter: "number",
		"description?": "string",
		"obsolete?": "boolean",
		"obsoleteReason?": "string",
		"unsigned?": "boolean",
		"isFloat?": "boolean",
	},

	InlineStructField: {
		"...": "TypeLayout",
		kind: "'inlineStruct'",
		fields: "FieldPlan[]",
	},

	VariantPlan: {
		name: "string",
		type: "Field",
	},

	/** Top-level type definitions */
	StructPlan: {
		"...": "TypeLayout",
		kind: "'struct'",
		name: "string",
		fields: "FieldPlan[]",
		"description?": "string",
		"obsolete?": "boolean",
		"obsoleteReason?": "string",
	},

	UnionPlan: {
		"...": "TypeLayout",
		kind: "'union'",
		name: "string",
		tagOffset: "number",
		tagSize: "number",
		tagType: "'u8' | 'u16' | 'u32'",
		variants: "VariantPlan[]",
		"description?": "string",
		"obsolete?": "boolean",
		"obsoleteReason?": "string",
		discriminant: "string?",
	},

	EnumVariant: {
		name: "string",
		value: "number",
		description: "string?",
	},

	EnumPlan: {
		"...": "TypeLayout",
		kind: "'enum'",
		name: "string",
		variants: "EnumVariant[]",
		underlyingType: "'u8' | 'u16' | 'i32'",
		"description?": "string",
		"obsolete?": "boolean",
		"obsoleteReason?": "string",
		"syntetic?": "boolean", // Was this type generated by analyzer?
	},

	AliasPlan: {
		"...": "TypeLayout",
		kind: "'alias'",
		name: "string",
		type: "Field",
		"targetOffset?": "number", // Binary offset of the aliased type
		"description?": "string",
		"obsolete?": "boolean",
		"obsoleteReason?": "string",
	},

	TypePlan: "StructPlan | UnionPlan | EnumPlan | AliasPlan",

	/** The complete Linear Layout Plan (LLP) */
	LayoutPlan: {
		"...": "PopSchemaSettings",
		types: "TypePlan[]",
	},
});

export const {
	AliasPlan,
	AnyField,
	ArrayField,
	EnumPlan,
	EnumVariant,
	Field,
	FieldPlan,
	InlineStructField,
	MapField,
	OptionalField,
	PrimitiveField,
	ReferenceField,
	StringField,
	StructPlan,
	UnionPlan,
	VariantPlan,
	TypePlan,
	TypeLayout,
	LayoutPlan,
} = $layout.export();

export type AliasPlan = typeof AliasPlan.infer;
export type AnyField = typeof AnyField.infer;
export type ArrayField = typeof ArrayField.infer;
export type EnumPlan = typeof EnumPlan.infer;
export type EnumVariant = typeof EnumVariant.infer;
export type Field = typeof Field.infer;
export type FieldPlan = typeof FieldPlan.infer;
export type InlineStructField = typeof InlineStructField.infer;
export type MapField = typeof MapField.infer;
export type OptionalField = typeof OptionalField.infer;
export type PrimitiveField = typeof PrimitiveField.infer;
export type ReferenceField = typeof ReferenceField.infer;
export type StringField = typeof StringField.infer;
export type StructPlan = typeof StructPlan.infer;
export type UnionPlan = typeof UnionPlan.infer;
export type VariantPlan = typeof VariantPlan.infer;
export type TypePlan = typeof TypePlan.infer;
export type TypeLayout = typeof TypeLayout.infer;
export type LayoutPlan = typeof LayoutPlan.infer;
