/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    Langs: typeof import('./src/components/Langs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TargetSelector: typeof import('./src/components/TargetSelector.vue')['default']
    USelect: typeof import('./../../node_modules/.bun/@nuxt+ui@4.7.1+e3b1e08466ecb3f3/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
  }
}

// For TSX support
declare global {
  const CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
  const FileUploader: typeof import('./src/components/FileUploader.vue')['default']
  const Langs: typeof import('./src/components/Langs.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TargetSelector: typeof import('./src/components/TargetSelector.vue')['default']
  const USelect: typeof import('./../../node_modules/.bun/@nuxt+ui@4.7.1+e3b1e08466ecb3f3/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
}