// AUTO-GENERATED by create-schema-pop. Run `bun run generate` to (re)emit
// every target artifact from your schema sources. Edit TARGETS / SETTINGS
// below to change what gets generated and where.
import { readdirSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import { fromModule, SchemaAnalyzer } from "@schema-pop/core";
import { exportPlan } from "@schema-pop/exporter";

const SCHEMA_PKG = join(import.meta.dir, "..");
const SCHEMA_SRC = join(SCHEMA_PKG, "src", "schema");

// Analyzer settings applied to every schema.
const SETTINGS = { wordSize: "64", endian: "le", mode: "binary" } as const;

// Output targets. Each schema is rendered to every target listed here.
// `dest` is resolved relative to this package's root.
const TARGETS: { target: string; dest: string; config?: Record<string, unknown> }[] = [
	{ target: "ts", dest: "../../packages/ts/src/schema.ts", config: { exportJsonPlan: true } },
	{ target: "ts:codec", dest: "../../packages/ts/src/codec.ts", config: { importPath: "./schema" } },
	{ target: "random", dest: "../../packages/ts/src/fixtures.json", config: { count: 8, seed: 42 } },
	{ target: "rust", dest: "../../packages/rust/src/schema.rs" },
	{ target: "rust:harness", dest: "../../packages/rust/src" },
	{ target: "cpp", dest: "../../packages/cpp/src/schema.hpp" },
	{ target: "c", dest: "../../packages/cpp/src/schema.h" },
	{ target: "cpp:harness", dest: "../../packages/cpp/src" },
	{ target: "zig", dest: "../../packages/zig/src/schema.zig", config: { pub: true } },
	{ target: "zig:harness", dest: "../../packages/zig/src" },
	{ target: "bf", dest: "../../packages/bf/schema.bf" },
	{ target: "bf:harness", dest: "../../packages/bf" },
	{ target: "html", dest: "./dist/schema.html" },
	{ target: "svg", dest: "./dist/svg" },
	{ target: "wgsl", dest: "./dist/schema.wgsl" },
	{ target: "random", dest: "./dist/random.json" },
];

// Highest-version file per `<name>.<version>.ts` family.
function latestSchemaFiles(): string[] {
	const best = new Map<string, { v: number[]; file: string }>();
	for (const f of readdirSync(SCHEMA_SRC)) {
		const m = f.match(/^(.+?)\.([0-9][0-9.]*)\.ts$/);
		if (!m) continue;
		const v = m[2]!.split(".").map(Number);
		const cur = best.get(m[1]!);
		if (!cur || cmp(v, cur.v) > 0) best.set(m[1]!, { v, file: f });
	}
	return [...best.values()].map((b) => b.file);
}
function cmp(a: number[], b: number[]): number {
	for (let i = 0; i < Math.max(a.length, b.length); i++) {
		const d = (a[i] ?? 0) - (b[i] ?? 0);
		if (d) return d;
	}
	return 0;
}

const analyzer = new SchemaAnalyzer();

for (const file of latestSchemaFiles()) {
	const mod = await import(pathToFileURL(join(SCHEMA_SRC, file)).href);
	const scope = mod.$ ?? mod.default;
	if (!scope?.export) {
		console.warn(`⚠ ${file}: no exported \`$\` arktype scope — skipping`);
		continue;
	}
	const { plan, warnings } = analyzer.analyze(fromModule(scope.export()), SETTINGS);
	for (const w of warnings) console.warn(`⚠ ${file}: ${w}`);

	for (const { target, dest, config } of TARGETS) {
		const out = exportPlan(plan, target as never, (config ?? {}) as never);
		if (typeof out === "string") {
			const outPath = join(SCHEMA_PKG, dest);
			await mkdir(dirname(outPath), { recursive: true });
			await Bun.write(outPath, out);
			console.log(`✅ ${target} → ${dest}`);
		} else {
			for (const [name, contents] of Object.entries(out)) {
				const outPath = join(SCHEMA_PKG, dest, name);
				await mkdir(dirname(outPath), { recursive: true });
				await Bun.write(outPath, contents as string);
			}
			console.log(`✅ ${target} → ${dest}/ (${Object.keys(out).length} files)`);
		}
	}
}

console.log("🍭 Schema generation complete.");
