// AUTO GENERATED BY schema-pop@0.1.41
// Schema: gpu-physics@1
// Layout: Little Endian
alias Vec2 = vec2<f32>;

alias Vec4 = vec4<f32>;

alias IVec2 = vec2<i32>;

struct Particle {
	friction: f32,
	mass: f32,
	object_data: u32,
	_pad_object_data: u32,
	pos: Vec2,
	prev_pos: Vec2,
	radius: f32,
	_pad_radius: u32,
};

struct Constraint {
	c_type_color: u32,
	compliance: f32,
	extra: Vec2,
	idx_a: i32,
	idx_b: i32,
	idx_c: i32,
	lambda: f32,
	rest_value: f32,
	_pad_rest_value: u32,
};

struct Obstacle {
	object_data: u32,
	_pad_object_data: array<u32, 3>,
	params: Vec4,
	pos: Vec2,
	rotation: f32,
	_pad_rotation: u32,
};

struct Params {
	collision_iterations: u32,
	dt: f32,
	erase_active: u32,
	_pad_erase_active: u32,
	erase_pos: Vec2,
	erase_radius_sq: f32,
	_pad_erase_radius_sq: u32,
	gravity: Vec2,
	is_paused: u32,
	mpm_damping: f32,
	mpm_domain_offset_x: f32,
	mpm_domain_offset_y: f32,
	mpm_dx: f32,
	mpm_grid_res: u32,
	mpm_inv_dx: f32,
	mpm_num_particles: u32,
	num_commands: u32,
	num_obstacles: u32,
	num_queries: u32,
	phase: u32,
	substeps: u32,
	_pad_substeps: u32,
	world_bounds: Vec4,
};

struct MpmParticle {
	bulk_modulus: f32,
	c00: f32,
	c01: f32,
	c10: f32,
	c11: f32,
	color: u32,
	f00: f32,
	f01: f32,
	f10: f32,
	f11: f32,
	gamma: f32,
	j: f32,
	mass: f32,
	_pad_mass: u32,
	pos: Vec2,
	type_mat: u32,
	_pad_type_mat: u32,
	vel: Vec2,
	volume: f32,
	_pad_volume: u32,
};

struct Command {
	cmd_type: u32,
	_pad_cmd_type: array<u32, 3>,
	d0: Vec4,
	d1: Vec4,
	index: u32,
	_pad_index: array<u32, 3>,
};

struct Query {
	dir_or_radius: Vec2,
	mask: u32,
	max_dist: f32,
	origin: Vec2,
	q_type: u32,
	_pad_q_type: u32,
};

struct QueryResult {
	count: u32,
	distance: f32,
	hit_idx: i32,
	_pad_hit_idx: u32,
	hit_normal: Vec2,
	hit_pos: Vec2,
	hit_type: u32,
	hits: array<i32, 16>,
	_pad_hits: u32,
};


