// AUTO GENERATED BY schema-pop@0.1.42
// Schema: showcase@1
// Layout: Little Endian
import { PopCodec } from "schema-pop";

export namespace showcase {
	export const TelemetryTag = {
		BatteryInfo: 0,
		Heartbeat: 1,
		PinnedRegisters: 2,
		SampleBatch: 3,
	} as const;
	export type TelemetryTag = "BatteryInfo" | "Heartbeat" | "PinnedRegisters" | "SampleBatch";

	/** { big_count: a bigint, count: non-negative and at most 4294967295, flag: boolean, nano_counter: a bigint, port: non-negative and at most 65535, precise_ratio: a number, ratio: a number, signed_giant: a bigint, signed_int: at least -2147483648 and at most 2147483647, signed_long: a bigint, signed_short: at least -32768 and at most 32767, small_signed: at least -128 and at most 127, small_unsigned: non-negative and at most 255 } */
	export interface AllScalars {
		/** a bigint */
		big_count: bigint;
		/** a bigint */
		nano_counter: bigint;
		/** a number */
		precise_ratio: number;
		/** a bigint */
		signed_giant: bigint;
		/** a bigint */
		signed_long: bigint;
		/** non-negative and at most 4294967295 */
		count: number;
		/** a number */
		ratio: number;
		/** at least -2147483648 and at most 2147483647 */
		signed_int: number;
		/** non-negative and at most 65535 */
		port: number;
		/** at least -32768 and at most 32767 */
		signed_short: number;
		/** boolean */
		flag: boolean;
		/** at least -128 and at most 127 */
		small_signed: number;
		/** non-negative and at most 255 */
		small_unsigned: number;
	}

	/** "Active", "Charging", "Error", "Idle", "LowBattery" or "Sleep" */
	export const Mode = {
		Active: 0,
		Charging: 1,
		Error: 2,
		Idle: 3,
		LowBattery: 4,
		Sleep: 5,
	} as const;
	export type Mode = "Active" | "Charging" | "Error" | "Idle" | "LowBattery" | "Sleep";

	/** "error", "fatal", "info" or "warn" */
	export const Severity = {
		error: 0,
		fatal: 1,
		info: 2,
		warn: 3,
	} as const;
	export type Severity = "error" | "fatal" | "info" | "warn";

	/** { enabled: non-negative and at most 1, mode_bits: non-negative and at most 7, retries: non-negative and at most 15 } */
	export interface StatusFlags {
		/** non-negative and at most 1 */
		enabled: unknown;
		/** non-negative and at most 7 */
		mode_bits: unknown;
		/** non-negative and at most 15 */
		retries: unknown;
	}

	/** { channel: non-negative and at most 15, fault: non-negative and at most 1, opcode: non-negative and at most 63, priority: non-negative and at most 15, ready: non-negative and at most 1 } */
	export interface ControlRegister {
		/** non-negative and at most 15 */
		channel: unknown;
		/** non-negative and at most 1 */
		fault: unknown;
		/** non-negative and at most 63 */
		opcode: unknown;
		/** non-negative and at most 15 */
		priority: unknown;
		/** non-negative and at most 1 */
		ready: unknown;
	}

	/** { _pad: non-negative and at most 255, charging: boolean, current: milliamps, signed, legacy_voltage: non-negative and at most 65535, serial_no: non-negative and at most 4294967295, temperature_c: at least -32768 and at most 32767, voltage: volts (mV raw → V scaled) } */
	export interface BatteryInfo {
		/** non-negative and at most 4294967295 */
		serial_no: number;
		/** milliamps, signed */
		current: number;
		/**
		 * non-negative and at most 65535
		 * @deprecated use voltage instead — kept for v1 firmware
		 */
		legacy_voltage: number;
		/** at least -32768 and at most 32767 */
		temperature_c: number;
		/** volts (mV raw → V scaled) */
		voltage: number;
		/** non-negative and at most 255 */
		_pad: number;
		/** boolean */
		charging: boolean;
	}

	/** { flags: { enabled: non-negative and at most 1, mode_bits: non-negative and at most 7, retries: non-negative and at most 15 }, precision: a number, timestamp: a bigint, value: at least -32768 and at most 32767, note?: a string } */
	export interface Sample {
		/** a bigint */
		timestamp: bigint;
		/** a number */
		precision: number;
		/** a string */
		note?: string;
		/** at least -32768 and at most 32767 */
		value: number;
		/** { enabled: non-negative and at most 1, mode_bits: non-negative and at most 7, retries: non-negative and at most 15 } */
		flags: StatusFlags;
	}

	/** { _pad: non-negative and at most 255, checksum: number <= 255 & >= 0[], count: non-negative and at most 65535, items: { flags: { enabled: number <= 1 & >= 0, mode_bits: number <= 7 & >= 0, retries: number <= 15 & >= 0 }, precision: number, timestamp: bigint, value: number <= 32767 & >= -32768, note?: string }[] } */
	export interface SampleBatch {
		/** { flags: { enabled: number <= 1 & >= 0, mode_bits: number <= 7 & >= 0, retries: number <= 15 & >= 0 }, precision: number, timestamp: bigint, value: number <= 32767 & >= -32768, note?: string }[] */
		items: Sample[];
		/** non-negative and at most 65535 */
		count: number;
		/** non-negative and at most 255 */
		_pad: number;
		/** number <= 255 & >= 0[] */
		checksum: number[];
	}

	/** { ctrl: non-negative and at most 4294967295, data: a bigint, status: non-negative and at most 4294967295 } */
	export interface PinnedRegisters {
		/** a bigint */
		data: bigint;
		/** non-negative and at most 4294967295 */
		ctrl: number;
		/** non-negative and at most 4294967295 */
		status: number;
	}

	/** { drift: a number, last_seen: a bigint, uptime: a bigint } */
	export interface Heartbeat {
		/** a number */
		drift: number;
		/** a bigint */
		last_seen: bigint;
		/** a bigint */
		uptime: bigint;
	}

	/** { _pad: non-negative and at most 255, charging: boolean, current: milliamps, signed, legacy_voltage: non-negative and at most 65535, serial_no: non-negative and at most 4294967295, temperature_c: at least -32768 and at most 32767, voltage: volts (mV raw → V scaled) }, { _pad: non-negative and at most 255, checksum: number <= 255 & >= 0[], count: non-negative and at most 65535, items: { flags: { enabled: number <= 1 & >= 0, mode_bits: number <= 7 & >= 0, retries: number <= 15 & >= 0 }, precision: number, timestamp: bigint, value: number <= 32767 & >= -32768, note?: string }[] }, { ctrl: non-negative and at most 4294967295, data: a bigint, status: non-negative and at most 4294967295 } or { drift: a number, last_seen: a bigint, uptime: a bigint } */
	export type Telemetry = ({ kind: "BatteryInfo" } & BatteryInfo) | ({ kind: "Heartbeat" } & Heartbeat) | ({ kind: "PinnedRegisters" } & PinnedRegisters) | ({ kind: "SampleBatch" } & SampleBatch);

	export const LAYOUT_PLAN = {
		"version": "showcase",
		"endian": "le",
		"autoLayout": true,
		"wordSize": 64,
		"types": [
			{
				"kind": "enum",
				"name": "TelemetryTag",
				"size": 1,
				"align": 1,
				"paddedSize": 1,
				"variants": [
					{
						"name": "BatteryInfo",
						"value": 0,
						"description": ""
					},
					{
						"name": "Heartbeat",
						"value": 1,
						"description": ""
					},
					{
						"name": "PinnedRegisters",
						"value": 2,
						"description": ""
					},
					{
						"name": "SampleBatch",
						"value": 3,
						"description": ""
					}
				],
				"underlyingType": "u8"
			},
			{
				"kind": "struct",
				"name": "AllScalars",
				"size": 80,
				"align": 8,
				"paddedSize": 80,
				"fields": [
					{
						"name": "big_count",
						"type": {
							"kind": "primitive",
							"size": 8,
							"align": 8,
							"paddedSize": 8,
							"name": "u64",
							"bitSize": 64,
							"popKind": "binary"
						},
						"offset": 0,
						"bitOffset": 0,
						"bitSize": 64,
						"size": 8,
						"paddingAfter": 0,
						"description": "a bigint"
					},
					{
						"name": "nano_counter",
						"type": {
							"kind": "primitive",
							"size": 16,
							"align": 8,
							"paddedSize": 16,
							"name": "u128",
							"bitSize": 128,
							"popKind": "binary"
						},
						"offset": 8,
						"bitOffset": 0,
						"bitSize": 128,
						"size": 16,
						"paddingAfter": 0,
						"description": "a bigint"
					},
					{
						"name": "precise_ratio",
						"type": {
							"kind": "primitive",
							"size": 8,
							"align": 8,
							"paddedSize": 8,
							"name": "f64",
							"bitSize": 64,
							"popKind": "binary"
						},
						"offset": 24,
						"bitOffset": 0,
						"bitSize": 64,
						"size": 8,
						"paddingAfter": 0,
						"description": "a number"
					},
					{
						"name": "signed_giant",
						"type": {
							"kind": "primitive",
							"size": 16,
							"align": 8,
							"paddedSize": 16,
							"name": "i128",
							"bitSize": 128,
							"popKind": "binary"
						},
						"offset": 32,
						"bitOffset": 0,
						"bitSize": 128,
						"size": 16,
						"paddingAfter": 0,
						"description": "a bigint"
					},
					{
						"name": "signed_long",
						"type": {
							"kind": "primitive",
							"size": 8,
							"align": 8,
							"paddedSize": 8,
							"name": "i64",
							"bitSize": 64,
							"popKind": "binary"
						},
						"offset": 48,
						"bitOffset": 0,
						"bitSize": 64,
						"size": 8,
						"paddingAfter": 0,
						"description": "a bigint"
					},
					{
						"name": "count",
						"type": {
							"kind": "primitive",
							"size": 4,
							"align": 4,
							"paddedSize": 4,
							"name": "u32",
							"bitSize": 32,
							"popKind": "binary"
						},
						"offset": 56,
						"bitOffset": 0,
						"bitSize": 32,
						"size": 4,
						"paddingAfter": 0,
						"description": "non-negative and at most 4294967295"
					},
					{
						"name": "ratio",
						"type": {
							"kind": "primitive",
							"size": 4,
							"align": 4,
							"paddedSize": 4,
							"name": "f32",
							"bitSize": 32,
							"popKind": "binary"
						},
						"offset": 60,
						"bitOffset": 0,
						"bitSize": 32,
						"size": 4,
						"paddingAfter": 0,
						"description": "a number"
					},
					{
						"name": "signed_int",
						"type": {
							"kind": "primitive",
							"size": 4,
							"align": 4,
							"paddedSize": 4,
							"name": "i32",
							"bitSize": 32,
							"popKind": "binary"
						},
						"offset": 64,
						"bitOffset": 0,
						"bitSize": 32,
						"size": 4,
						"paddingAfter": 0,
						"description": "at least -2147483648 and at most 2147483647"
					},
					{
						"name": "port",
						"type": {
							"kind": "primitive",
							"size": 2,
							"align": 2,
							"paddedSize": 2,
							"name": "u16",
							"bitSize": 16,
							"popKind": "binary"
						},
						"offset": 68,
						"bitOffset": 0,
						"bitSize": 16,
						"size": 2,
						"paddingAfter": 0,
						"description": "non-negative and at most 65535"
					},
					{
						"name": "signed_short",
						"type": {
							"kind": "primitive",
							"size": 2,
							"align": 2,
							"paddedSize": 2,
							"name": "i16",
							"bitSize": 16,
							"popKind": "binary"
						},
						"offset": 70,
						"bitOffset": 0,
						"bitSize": 16,
						"size": 2,
						"paddingAfter": 0,
						"description": "at least -32768 and at most 32767"
					},
					{
						"name": "flag",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "bool",
							"bitSize": 8,
							"popKind": "binary"
						},
						"offset": 72,
						"bitOffset": 0,
						"bitSize": 8,
						"size": 1,
						"paddingAfter": 0,
						"description": "boolean"
					},
					{
						"name": "small_signed",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "i8",
							"bitSize": 8,
							"popKind": "binary"
						},
						"offset": 73,
						"bitOffset": 0,
						"bitSize": 8,
						"size": 1,
						"paddingAfter": 0,
						"description": "at least -128 and at most 127"
					},
					{
						"name": "small_unsigned",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "u8",
							"bitSize": 8,
							"popKind": "binary"
						},
						"offset": 74,
						"bitOffset": 0,
						"bitSize": 8,
						"size": 1,
						"paddingAfter": 5,
						"description": "non-negative and at most 255"
					}
				],
				"description": "{ big_count: a bigint, count: non-negative and at most 4294967295, flag: boolean, nano_counter: a bigint, port: non-negative and at most 65535, precise_ratio: a number, ratio: a number, signed_giant: a bigint, signed_int: at least -2147483648 and at most 2147483647, signed_long: a bigint, signed_short: at least -32768 and at most 32767, small_signed: at least -128 and at most 127, small_unsigned: non-negative and at most 255 }"
			},
			{
				"kind": "enum",
				"name": "Mode",
				"size": 1,
				"align": 1,
				"paddedSize": 1,
				"variants": [
					{
						"name": "Active",
						"value": 0
					},
					{
						"name": "Charging",
						"value": 1
					},
					{
						"name": "Error",
						"value": 2
					},
					{
						"name": "Idle",
						"value": 3
					},
					{
						"name": "LowBattery",
						"value": 4
					},
					{
						"name": "Sleep",
						"value": 5
					}
				],
				"underlyingType": "u8",
				"description": "\"Active\", \"Charging\", \"Error\", \"Idle\", \"LowBattery\" or \"Sleep\""
			},
			{
				"kind": "enum",
				"name": "Severity",
				"size": 1,
				"align": 1,
				"paddedSize": 1,
				"variants": [
					{
						"name": "error",
						"value": 0
					},
					{
						"name": "fatal",
						"value": 1
					},
					{
						"name": "info",
						"value": 2
					},
					{
						"name": "warn",
						"value": 3
					}
				],
				"underlyingType": "u8",
				"description": "\"error\", \"fatal\", \"info\" or \"warn\""
			},
			{
				"kind": "struct",
				"name": "StatusFlags",
				"size": 1,
				"align": 1,
				"paddedSize": 1,
				"fields": [
					{
						"name": "enabled",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "u1",
							"bitSize": 1,
							"popKind": "binary"
						},
						"offset": 0,
						"bitOffset": 0,
						"bitSize": 1,
						"size": 1,
						"paddingAfter": 0,
						"description": "non-negative and at most 1"
					},
					{
						"name": "mode_bits",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "u3",
							"bitSize": 3,
							"popKind": "binary"
						},
						"offset": 0,
						"bitOffset": 1,
						"bitSize": 3,
						"size": 1,
						"paddingAfter": 0,
						"description": "non-negative and at most 7"
					},
					{
						"name": "retries",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "u4",
							"bitSize": 4,
							"popKind": "binary"
						},
						"offset": 0,
						"bitOffset": 4,
						"bitSize": 4,
						"size": 1,
						"paddingAfter": 0,
						"description": "non-negative and at most 15"
					}
				],
				"description": "{ enabled: non-negative and at most 1, mode_bits: non-negative and at most 7, retries: non-negative and at most 15 }"
			},
			{
				"kind": "struct",
				"name": "ControlRegister",
				"size": 3,
				"align": 1,
				"paddedSize": 3,
				"fields": [
					{
						"name": "channel",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "u4",
							"bitSize": 4,
							"popKind": "binary"
						},
						"offset": 0,
						"bitOffset": 0,
						"bitSize": 4,
						"size": 1,
						"paddingAfter": 0,
						"description": "non-negative and at most 15"
					},
					{
						"name": "fault",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "u1",
							"bitSize": 1,
							"popKind": "binary"
						},
						"offset": 0,
						"bitOffset": 4,
						"bitSize": 1,
						"size": 1,
						"paddingAfter": 0,
						"description": "non-negative and at most 1"
					},
					{
						"name": "opcode",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "u6",
							"bitSize": 6,
							"popKind": "binary"
						},
						"offset": 1,
						"bitOffset": 0,
						"bitSize": 6,
						"size": 1,
						"paddingAfter": 0,
						"description": "non-negative and at most 63"
					},
					{
						"name": "priority",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "u4",
							"bitSize": 4,
							"popKind": "binary"
						},
						"offset": 2,
						"bitOffset": 0,
						"bitSize": 4,
						"size": 1,
						"paddingAfter": 0,
						"description": "non-negative and at most 15"
					},
					{
						"name": "ready",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "u1",
							"bitSize": 1,
							"popKind": "binary"
						},
						"offset": 2,
						"bitOffset": 4,
						"bitSize": 1,
						"size": 1,
						"paddingAfter": 0,
						"description": "non-negative and at most 1"
					}
				],
				"description": "{ channel: non-negative and at most 15, fault: non-negative and at most 1, opcode: non-negative and at most 63, priority: non-negative and at most 15, ready: non-negative and at most 1 }"
			},
			{
				"kind": "struct",
				"name": "BatteryInfo",
				"size": 16,
				"align": 4,
				"paddedSize": 16,
				"fields": [
					{
						"name": "serial_no",
						"type": {
							"kind": "primitive",
							"size": 4,
							"align": 4,
							"paddedSize": 4,
							"name": "u32",
							"bitSize": 32,
							"popKind": "binary"
						},
						"offset": 0,
						"bitOffset": 0,
						"bitSize": 32,
						"size": 4,
						"paddingAfter": 0,
						"description": "non-negative and at most 4294967295",
						"migrationMeta": {
							"renamedFrom": "device_id"
						}
					},
					{
						"name": "current",
						"type": {
							"kind": "primitive",
							"size": 2,
							"align": 2,
							"paddedSize": 2,
							"name": "i16",
							"bitSize": 16,
							"popKind": "binary"
						},
						"offset": 4,
						"bitOffset": 0,
						"bitSize": 16,
						"size": 2,
						"paddingAfter": 0,
						"description": "milliamps, signed"
					},
					{
						"name": "legacy_voltage",
						"type": {
							"kind": "primitive",
							"size": 2,
							"align": 2,
							"paddedSize": 2,
							"name": "u16",
							"bitSize": 16,
							"popKind": "binary"
						},
						"offset": 6,
						"bitOffset": 0,
						"bitSize": 16,
						"size": 2,
						"paddingAfter": 0,
						"description": "non-negative and at most 65535",
						"obsolete": true,
						"obsoleteReason": "use voltage instead — kept for v1 firmware"
					},
					{
						"name": "temperature_c",
						"type": {
							"kind": "primitive",
							"size": 2,
							"align": 2,
							"paddedSize": 2,
							"name": "i16",
							"bitSize": 16,
							"popKind": "binary"
						},
						"offset": 8,
						"bitOffset": 0,
						"bitSize": 16,
						"size": 2,
						"paddingAfter": 0,
						"description": "at least -32768 and at most 32767"
					},
					{
						"name": "voltage",
						"type": {
							"kind": "primitive",
							"size": 2,
							"align": 2,
							"paddedSize": 2,
							"name": "u16",
							"bitSize": 16,
							"popKind": "binary"
						},
						"offset": 10,
						"bitOffset": 0,
						"bitSize": 16,
						"size": 2,
						"paddingAfter": 0,
						"description": "volts (mV raw → V scaled)"
					},
					{
						"name": "_pad",
						"type": {
							"kind": "primitive",
							"name": "u8",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"bitSize": 8,
							"popKind": "binary"
						},
						"offset": 12,
						"bitOffset": 0,
						"bitSize": 8,
						"size": 1,
						"paddingAfter": 0,
						"description": "non-negative and at most 255"
					},
					{
						"name": "charging",
						"type": {
							"kind": "primitive",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"name": "bool",
							"bitSize": 8,
							"popKind": "binary"
						},
						"offset": 13,
						"bitOffset": 0,
						"bitSize": 8,
						"size": 1,
						"paddingAfter": 2,
						"description": "boolean"
					}
				],
				"description": "{ _pad: non-negative and at most 255, charging: boolean, current: milliamps, signed, legacy_voltage: non-negative and at most 65535, serial_no: non-negative and at most 4294967295, temperature_c: at least -32768 and at most 32767, voltage: volts (mV raw → V scaled) }"
			},
			{
				"kind": "struct",
				"name": "Sample",
				"size": 24,
				"align": 8,
				"paddedSize": 24,
				"fields": [
					{
						"name": "timestamp",
						"type": {
							"kind": "primitive",
							"size": 8,
							"align": 8,
							"paddedSize": 8,
							"name": "i64",
							"bitSize": 64,
							"popKind": "binary"
						},
						"offset": 0,
						"bitOffset": 0,
						"bitSize": 64,
						"size": 8,
						"paddingAfter": 0,
						"description": "a bigint"
					},
					{
						"name": "precision",
						"type": {
							"kind": "primitive",
							"size": 4,
							"align": 4,
							"paddedSize": 4,
							"name": "f32",
							"bitSize": 32,
							"popKind": "binary"
						},
						"offset": 8,
						"bitOffset": 0,
						"bitSize": 32,
						"size": 4,
						"paddingAfter": 0,
						"description": "a number"
					},
					{
						"name": "note",
						"type": {
							"kind": "optional",
							"inner": {
								"kind": "string"
							}
						},
						"offset": 12,
						"bitOffset": 0,
						"bitSize": 64,
						"size": 8,
						"paddingAfter": 0,
						"description": "a string"
					},
					{
						"name": "value",
						"type": {
							"kind": "primitive",
							"size": 2,
							"align": 2,
							"paddedSize": 2,
							"name": "i16",
							"bitSize": 16,
							"popKind": "binary"
						},
						"offset": 20,
						"bitOffset": 0,
						"bitSize": 16,
						"size": 2,
						"paddingAfter": 0,
						"description": "at least -32768 and at most 32767"
					},
					{
						"name": "flags",
						"type": {
							"kind": "reference",
							"name": "StatusFlags",
							"indirection": "inline",
							"isForward": false
						},
						"offset": 22,
						"bitOffset": 0,
						"bitSize": 8,
						"size": 1,
						"paddingAfter": 1,
						"description": "{ enabled: non-negative and at most 1, mode_bits: non-negative and at most 7, retries: non-negative and at most 15 }"
					}
				],
				"description": "{ flags: { enabled: non-negative and at most 1, mode_bits: non-negative and at most 7, retries: non-negative and at most 15 }, precision: a number, timestamp: a bigint, value: at least -32768 and at most 32767, note?: a string }"
			},
			{
				"kind": "struct",
				"name": "SampleBatch",
				"size": 1568,
				"align": 8,
				"paddedSize": 1568,
				"fields": [
					{
						"name": "items",
						"type": {
							"kind": "array",
							"item": {
								"kind": "reference",
								"name": "Sample",
								"indirection": "inline",
								"isForward": false
							},
							"maxLength": 64
						},
						"offset": 0,
						"bitOffset": 0,
						"bitSize": 12320,
						"size": 1540,
						"paddingAfter": 0,
						"description": "{ flags: { enabled: number <= 1 & >= 0, mode_bits: number <= 7 & >= 0, retries: number <= 15 & >= 0 }, precision: number, timestamp: bigint, value: number <= 32767 & >= -32768, note?: string }[]"
					},
					{
						"name": "count",
						"type": {
							"kind": "primitive",
							"size": 2,
							"align": 2,
							"paddedSize": 2,
							"name": "u16",
							"bitSize": 16,
							"popKind": "binary"
						},
						"offset": 1544,
						"bitOffset": 0,
						"bitSize": 16,
						"size": 2,
						"paddingAfter": 0,
						"description": "non-negative and at most 65535"
					},
					{
						"name": "_pad",
						"type": {
							"kind": "primitive",
							"name": "u8",
							"size": 1,
							"align": 1,
							"paddedSize": 1,
							"bitSize": 8,
							"popKind": "binary"
						},
						"offset": 1546,
						"bitOffset": 0,
						"bitSize": 8,
						"size": 1,
						"paddingAfter": 0,
						"description": "non-negative and at most 255"
					},
					{
						"name": "checksum",
						"type": {
							"kind": "array",
							"item": {
								"kind": "primitive",
								"size": 1,
								"align": 1,
								"paddedSize": 1,
								"name": "u8",
								"bitSize": 8,
								"popKind": "binary"
							},
							"exactLength": 16
						},
						"offset": 1547,
						"bitOffset": 0,
						"bitSize": 128,
						"size": 16,
						"paddingAfter": 5,
						"description": "number <= 255 & >= 0[]"
					}
				],
				"description": "{ _pad: non-negative and at most 255, checksum: number <= 255 & >= 0[], count: non-negative and at most 65535, items: { flags: { enabled: number <= 1 & >= 0, mode_bits: number <= 7 & >= 0, retries: number <= 15 & >= 0 }, precision: number, timestamp: bigint, value: number <= 32767 & >= -32768, note?: string }[] }"
			},
			{
				"kind": "struct",
				"name": "PinnedRegisters",
				"size": 16,
				"align": 8,
				"paddedSize": 16,
				"fields": [
					{
						"name": "data",
						"type": {
							"kind": "primitive",
							"size": 8,
							"align": 8,
							"paddedSize": 8,
							"name": "u64",
							"bitSize": 64,
							"popKind": "binary"
						},
						"offset": 0,
						"bitOffset": 0,
						"bitSize": 64,
						"size": 8,
						"paddingAfter": 0,
						"description": "a bigint"
					},
					{
						"name": "ctrl",
						"type": {
							"kind": "primitive",
							"size": 4,
							"align": 4,
							"paddedSize": 4,
							"name": "u32",
							"bitSize": 32,
							"popKind": "binary"
						},
						"offset": 8,
						"bitOffset": 0,
						"bitSize": 32,
						"size": 4,
						"paddingAfter": 0,
						"description": "non-negative and at most 4294967295"
					},
					{
						"name": "status",
						"type": {
							"kind": "primitive",
							"size": 4,
							"align": 4,
							"paddedSize": 4,
							"name": "u32",
							"bitSize": 32,
							"popKind": "binary"
						},
						"offset": 12,
						"bitOffset": 0,
						"bitSize": 32,
						"size": 4,
						"paddingAfter": 0,
						"description": "non-negative and at most 4294967295"
					}
				],
				"description": "{ ctrl: non-negative and at most 4294967295, data: a bigint, status: non-negative and at most 4294967295 }"
			},
			{
				"kind": "struct",
				"name": "Heartbeat",
				"size": 24,
				"align": 8,
				"paddedSize": 24,
				"fields": [
					{
						"name": "drift",
						"type": {
							"kind": "primitive",
							"size": 8,
							"align": 8,
							"paddedSize": 8,
							"name": "f64",
							"bitSize": 64,
							"popKind": "binary"
						},
						"offset": 0,
						"bitOffset": 0,
						"bitSize": 64,
						"size": 8,
						"paddingAfter": 0,
						"description": "a number"
					},
					{
						"name": "last_seen",
						"type": {
							"kind": "primitive",
							"size": 8,
							"align": 8,
							"paddedSize": 8,
							"name": "i64",
							"bitSize": 64,
							"popKind": "binary"
						},
						"offset": 8,
						"bitOffset": 0,
						"bitSize": 64,
						"size": 8,
						"paddingAfter": 0,
						"description": "a bigint"
					},
					{
						"name": "uptime",
						"type": {
							"kind": "primitive",
							"size": 8,
							"align": 8,
							"paddedSize": 8,
							"name": "u64",
							"bitSize": 64,
							"popKind": "binary"
						},
						"offset": 16,
						"bitOffset": 0,
						"bitSize": 64,
						"size": 8,
						"paddingAfter": 0,
						"description": "a bigint"
					}
				],
				"description": "{ drift: a number, last_seen: a bigint, uptime: a bigint }"
			},
			{
				"kind": "union",
				"name": "Telemetry",
				"size": 1576,
				"align": 8,
				"paddedSize": 1576,
				"tagOffset": 0,
				"tagSize": 1,
				"tagType": "u8",
				"variants": [
					{
						"name": "BatteryInfo",
						"type": {
							"kind": "reference",
							"name": "BatteryInfo",
							"indirection": "inline",
							"isForward": false
						}
					},
					{
						"name": "Heartbeat",
						"type": {
							"kind": "reference",
							"name": "Heartbeat",
							"indirection": "inline",
							"isForward": false
						}
					},
					{
						"name": "PinnedRegisters",
						"type": {
							"kind": "reference",
							"name": "PinnedRegisters",
							"indirection": "inline",
							"isForward": false
						}
					},
					{
						"name": "SampleBatch",
						"type": {
							"kind": "reference",
							"name": "SampleBatch",
							"indirection": "inline",
							"isForward": false
						}
					}
				],
				"description": "{ _pad: non-negative and at most 255, charging: boolean, current: milliamps, signed, legacy_voltage: non-negative and at most 65535, serial_no: non-negative and at most 4294967295, temperature_c: at least -32768 and at most 32767, voltage: volts (mV raw → V scaled) }, { _pad: non-negative and at most 255, checksum: number <= 255 & >= 0[], count: non-negative and at most 65535, items: { flags: { enabled: number <= 1 & >= 0, mode_bits: number <= 7 & >= 0, retries: number <= 15 & >= 0 }, precision: number, timestamp: bigint, value: number <= 32767 & >= -32768, note?: string }[] }, { ctrl: non-negative and at most 4294967295, data: a bigint, status: non-negative and at most 4294967295 } or { drift: a number, last_seen: a bigint, uptime: a bigint }"
			}
		]
	} as const;

	const _codec = new PopCodec(LAYOUT_PLAN as any);

	export const TelemetryTagCodec = {
		encode: (data: TelemetryTag): Uint8Array => _codec.encode("TelemetryTag", data),
		decode: (buf: Uint8Array): TelemetryTag => _codec.decode("TelemetryTag", buf) as TelemetryTag,
	};
	export const AllScalarsCodec = {
		encode: (data: AllScalars): Uint8Array => _codec.encode("AllScalars", data),
		decode: (buf: Uint8Array): AllScalars => _codec.decode("AllScalars", buf) as AllScalars,
	};
	export const ModeCodec = {
		encode: (data: Mode): Uint8Array => _codec.encode("Mode", data),
		decode: (buf: Uint8Array): Mode => _codec.decode("Mode", buf) as Mode,
	};
	export const SeverityCodec = {
		encode: (data: Severity): Uint8Array => _codec.encode("Severity", data),
		decode: (buf: Uint8Array): Severity => _codec.decode("Severity", buf) as Severity,
	};
	export const StatusFlagsCodec = {
		encode: (data: StatusFlags): Uint8Array => _codec.encode("StatusFlags", data),
		decode: (buf: Uint8Array): StatusFlags => _codec.decode("StatusFlags", buf) as StatusFlags,
	};
	export const ControlRegisterCodec = {
		encode: (data: ControlRegister): Uint8Array => _codec.encode("ControlRegister", data),
		decode: (buf: Uint8Array): ControlRegister => _codec.decode("ControlRegister", buf) as ControlRegister,
	};
	export const BatteryInfoCodec = {
		encode: (data: BatteryInfo): Uint8Array => _codec.encode("BatteryInfo", data),
		decode: (buf: Uint8Array): BatteryInfo => _codec.decode("BatteryInfo", buf) as BatteryInfo,
	};
	export const SampleCodec = {
		encode: (data: Sample): Uint8Array => _codec.encode("Sample", data),
		decode: (buf: Uint8Array): Sample => _codec.decode("Sample", buf) as Sample,
	};
	export const SampleBatchCodec = {
		encode: (data: SampleBatch): Uint8Array => _codec.encode("SampleBatch", data),
		decode: (buf: Uint8Array): SampleBatch => _codec.decode("SampleBatch", buf) as SampleBatch,
	};
	export const PinnedRegistersCodec = {
		encode: (data: PinnedRegisters): Uint8Array => _codec.encode("PinnedRegisters", data),
		decode: (buf: Uint8Array): PinnedRegisters => _codec.decode("PinnedRegisters", buf) as PinnedRegisters,
	};
	export const HeartbeatCodec = {
		encode: (data: Heartbeat): Uint8Array => _codec.encode("Heartbeat", data),
		decode: (buf: Uint8Array): Heartbeat => _codec.decode("Heartbeat", buf) as Heartbeat,
	};
	export const TelemetryCodec = {
		encode: (data: Telemetry): Uint8Array => _codec.encode("Telemetry", data),
		decode: (buf: Uint8Array): Telemetry => _codec.decode("Telemetry", buf) as Telemetry,
	};
}

