/// <reference types="node" />

import fs from "node:fs";
import path from "node:path";
import { createJiti } from "jiti";

/**
 * Detects an arktype Scope by duck-typing — anything with `.export()` and
 * `.import()` as functions counts. Avoids importing arktype's Scope type
 * here because we want bind to keep working if upstream renames the class.
 */
export function isArktypeScope(
	v: unknown,
): v is { export: () => Record<string, unknown>; import: () => unknown } {
	return (
		typeof v === "object" &&
		v !== null &&
		typeof (v as any).export === "function" &&
		typeof (v as any).import === "function"
	);
}

interface ScopeBinding {
	varName: string;
	aliases: string[];
}

function renderBindings(scopes: ScopeBinding[]): string {
	const lines: string[] = [];
	lines.push("// ---- schema-pop bindings (auto-generated, do not edit) ----");
	for (const { varName, aliases } of scopes) {
		if (aliases.length === 0) {
			lines.push("");
			lines.push(`// (scope ${varName} has no aliases)`);
			continue;
		}
		lines.push("");
		lines.push(`export const {`);
		for (const name of aliases) lines.push(`\t${name},`);
		lines.push(`} = ${varName}.export();`);
		lines.push("");
		for (const name of aliases) {
			lines.push(`export type ${name} = typeof ${name}.infer;`);
		}
	}
	return lines.join("\n") + "\n";
}

export interface BindResult {
	source: string;
	dest: string;
	scopes: ScopeBinding[];
}

/**
 * Reads a TypeScript source file containing one or more arktype scope exports,
 * appends destructured `export const {...} = $scope.export()` plus matching
 * `export type X = typeof X.infer` lines, and writes the result to `destPath`.
 *
 * The original file content is preserved verbatim — relative imports stay
 * pointing at whatever the source pointed at; how the user organises their
 * dist tree is their problem to solve via dest paths.
 */
export async function bindFile(
	sourcePath: string,
	destPath: string,
): Promise<BindResult> {
	const absSource = path.resolve(sourcePath);
	if (!fs.existsSync(absSource)) {
		throw new Error(`schema-pop bind: source not found: ${sourcePath}`);
	}

	const sourceContent = fs.readFileSync(absSource, "utf8");
	const jiti = createJiti(import.meta.url);
	const mod = (await jiti.import(absSource)) as Record<string, unknown>;

	const scopes: ScopeBinding[] = [];
	const seen = new Map<string, string>();

	for (const [varName, val] of Object.entries(mod)) {
		if (!isArktypeScope(val)) continue;
		let exported: Record<string, unknown>;
		try {
			exported = val.export();
		} catch (e) {
			console.warn(
				`  ⚠ schema-pop bind: ${varName}.export() threw, skipping (${(e as Error).message})`,
			);
			continue;
		}
		const aliases = Object.keys(exported);
		for (const a of aliases) {
			const owner = seen.get(a);
			if (owner) {
				throw new Error(
					`schema-pop bind: alias "${a}" is exported by both ${owner} and ${varName} in ${sourcePath} — cannot emit non-conflicting destructure`,
				);
			}
			seen.set(a, varName);
		}
		scopes.push({ varName, aliases });
	}

	if (scopes.length === 0) {
		throw new Error(
			`schema-pop bind: no arktype scope exports found in ${sourcePath}`,
		);
	}

	const header = `// Generated by schema-pop bind. Do not edit — see ${path.basename(absSource)}\n`;
	const finalContent = `${header}\n${sourceContent.trimEnd()}\n\n${renderBindings(scopes)}`;

	const absDest = path.resolve(destPath);
	const destDir = path.dirname(absDest);
	if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
	fs.writeFileSync(absDest, finalContent);

	return { source: absSource, dest: absDest, scopes };
}

export interface BindingSpec {
	/** File or glob pattern (resolved against cwd). */
	source: string;
	/** Output file (if exact path) or directory (if ends with `/` or already exists as dir). */
	dest: string;
}

/**
 * Resolves dest for a single source: if `dest` ends with `/` or is an existing
 * directory, treat as a folder and mirror the source basename. Otherwise treat
 * as exact file path.
 */
function resolveDest(sourceAbs: string, destSpec: string, cwd: string): string {
	const isDir = destSpec.endsWith("/") || destSpec.endsWith(path.sep);
	const absDest = path.resolve(cwd, destSpec);
	if (isDir || (fs.existsSync(absDest) && fs.statSync(absDest).isDirectory())) {
		return path.join(absDest, path.basename(sourceAbs));
	}
	return absDest;
}

/**
 * Expands glob patterns and runs `bindFile` for each matched source. Designed
 * to be invoked from the CLI (`schema-pop bind`) or directly from a build
 * script — never from the regular `schema-pop` (build/generate) flow, since
 * the build pipeline must stay free of side-effectful code generation.
 */
export async function runBindings(
	specs: BindingSpec[],
	cwd: string = process.cwd(),
): Promise<BindResult[]> {
	const results: BindResult[] = [];
	for (const spec of specs) {
		const hasGlob = spec.source.includes("*") || spec.source.includes("?");
		const sources: string[] = [];
		if (hasGlob) {
			// Bun.Glob is the simplest cross-platform option; we depend on bun
			// for the CLI runtime anyway (cli.ts uses #!/usr/bin/env bun).
			const glob = new (globalThis as any).Bun.Glob(spec.source);
			for (const file of glob.scanSync({ cwd, absolute: true })) {
				sources.push(file as string);
			}
			if (sources.length === 0) {
				console.warn(`  ⚠ schema-pop bind: no files matched "${spec.source}"`);
				continue;
			}
		} else {
			sources.push(path.resolve(cwd, spec.source));
		}

		for (const sourceAbs of sources) {
			const destPath = resolveDest(sourceAbs, spec.dest, cwd);
			const res = await bindFile(sourceAbs, destPath);
			console.log(
				`✅ [schema-pop bind] ${path.relative(cwd, res.source)} → ${path.relative(cwd, res.dest)}`,
			);
			results.push(res);
		}
	}
	return results;
}
