import fs from "node:fs";
import path from "node:path";
import { createJiti } from "jiti";
import { SchemaAnalyzer } from "./layout/analyzer";
import type { ExporterPlugin, LayoutPlan } from "./schema/index";
import { renderComment } from "./utils/comments";

export async function buildConfig(configPath: string, ctx?: { addWatchFile?: (p: string) => void }) {
	const jiti = createJiti(import.meta.url);
	const resolvedPath = path.resolve(process.cwd(), configPath);
	if (!fs.existsSync(resolvedPath)) {
		throw new Error(`Configuration file not found: ${resolvedPath}`);
	}
	const rootDir = path.dirname(resolvedPath);
	const configModule = (await jiti.import(resolvedPath)) as any;
	const config = configModule.default || configModule.config || configModule;
	await buildSchema(config, rootDir, ctx);
}

export function generateTypes(schema: LayoutPlan, target: ExporterPlugin<any>) {
	const config = target.config;
	let code = target.generate(schema);
	if (typeof code === "string" && code && !config.noWrap) {
		return code;
	}
	return code;
}

export async function buildSchema(config: any, rootDir: string, ctx?: { addWatchFile?: (p: string) => void }) {
	const jiti = createJiti(import.meta.url);
	const targetContents: Record<string, { 
		targetConfig: any; 
		targetInstance: ExporterPlugin<any>; 
		body: string; 
		plans: LayoutPlan[] 
	}> = {};

	for (const schema of config.schemas || []) {
		const versions = schema.versions || [];
		const targets = schema.targets || config.targets || [];
		let previousVersion: string | null = null;
		let previousPlan: LayoutPlan | null = null;

		for (let i = 0; i < versions.length; i++) {
			const v = versions[i]!;
			const safeVersion = schema.name ? `${schema.name}_${v.version}` : v.version;
			const isLatest = i === versions.length - 1;
			const filePath = path.resolve(rootDir, v.source.endsWith(".ts") ? v.source : v.source + ".ts");

			if (!fs.existsSync(filePath)) {
				console.error(`❌ [Schema-Pop] File not found: ${filePath}`);
				continue;
			}

			if (ctx?.addWatchFile) ctx.addWatchFile(filePath);

			const module = (await jiti.import(filePath)) as any;
			const exportName = v.exportName || "$";
			const scope = module[exportName] || module[schema.name];

			if (!scope) {
				console.error(`❌ [Schema-Pop] No export found in ${filePath}.`);
				continue;
			}

			const analyzer = new SchemaAnalyzer(scope, {
				wordSize: config.wordSize,
				autoLayout: config.autoLayout,
				layoutType: config.layout || "aligned"
			});
			const plan = analyzer.analyze(safeVersion, config.endian || "le");

			for (const target of targets) {
				const instance = target as ExporterPlugin<any>;
				const targetConfig = instance.config;
				const dest = targetConfig.dest;

				if (!dest) continue;

				if (!instance.wrapVersion && versions.length > 1) {
					if (!isLatest) continue;
					console.warn(`⚠️  [Schema-Pop] Exporter "${instance.name}" only supports a single version! Only latest schema version will be exported to ${dest}`);
				}

				let content = instance.generate(plan);

				if (typeof content === "string") {
					if (!targetContents[dest]) {
						targetContents[dest] = { targetConfig, targetInstance: instance, body: "", plans: [] };
					}
					const entry = targetContents[dest]!;
					entry.plans.push(plan);

					if (instance.wrapVersion) {
						content = instance.wrapVersion(safeVersion, content);
					}
					entry.body += `${content}\n`;

					if (instance.wrapVersion && previousVersion && previousPlan && instance.generateMigration) {
						const migration = instance.generateMigration(previousPlan, plan);
						if (migration) entry.body += `\n${migration}\n`;
					}
				} else {
					for (const [filename, subContent] of Object.entries(content)) {
						const fileDest = path.join(dest, filename);
						if (!targetContents[fileDest]) {
							targetContents[fileDest] = { targetConfig, targetInstance: instance, body: "", plans: [] };
						}
						targetContents[fileDest].plans.push(plan);
						targetContents[fileDest].body += (subContent as string) + "\n";
					}
				}
			}
			previousVersion = safeVersion;
			previousPlan = plan;
		}
	}

	for (const dest in targetContents) {
		const entry = targetContents[dest]!;
		const { targetInstance, targetConfig } = entry;
		const absDest = path.resolve(rootDir, dest);
		
		let finalFile = "";
		if (!targetConfig.noHeader) {
			const endianStr = config.endian === "be" ? "Big Endian" : "Little Endian";
			const header = renderComment(targetConfig.commentStyle ?? "slash", `AUTO GENERATED BY SCHEMA-POP\nLayout: ${endianStr}`);
			if (header) finalFile += header + "\n";
		}

		if (targetInstance.getFileHeader) {
			finalFile += targetInstance.getFileHeader() + "\n";
		}

		if (targetConfig.prependToFile) finalFile += targetConfig.prependToFile + "\n";
		finalFile += entry.body;
		if (targetConfig.appendToFile) finalFile += targetConfig.appendToFile + "\n";

		if (targetInstance.getFileFooter) {
			finalFile += targetInstance.getFileFooter();
		}

		const dir = path.extname(absDest) ? path.dirname(absDest) : absDest;
		if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

		if (path.extname(absDest)) {
			fs.writeFileSync(absDest, finalFile);
			console.log(`✅ [Schema-Pop] Generated: ${dest}`);
		}

		if (targetInstance.getHarness) {
			const harnessFiles = targetInstance.getHarness(entry.plans);
			for (const [filename, fileContent] of Object.entries(harnessFiles)) {
				const harnessDest = path.resolve(dir, filename);
				const hDir = path.dirname(harnessDest);
				if (!fs.existsSync(hDir)) fs.mkdirSync(hDir, { recursive: true });
				fs.writeFileSync(harnessDest, fileContent as string);
				console.log(`✅ [Schema-Pop] Harness File: ${path.relative(rootDir, harnessDest)}`);
			}
		}
	}
}
