/// <reference types="@types/bun" />
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { $ } from "bun";
import { scope } from "arktype";
import { createRuntimeCodec, fromModule, SchemaAnalyzer } from "@schema-pop/core";
import { binary, type LayoutPlan } from "@schema-pop/schema";
import { exportPlan } from "@schema-pop/exporter";

/**
 * Cross-language ABI verification.
 *
 * The predecessor of this test copied a committed scaffold fixture
 * (`verdaccio/tmp_test/integration-test-project`) that was generated by
 * `packages/create`. Both the fixture and `packages/create` are gone, so the
 * test could never get past `cpSync`. Nothing about the ABI check actually
 * needed a scaffolded npm project — the harness programs are just the output
 * of the `<lang>:harness` exporters. So this version generates everything
 * in-process from a schema declared right here:
 *
 *   1. analyze a schema that stresses layout (padding, nesting, align-8,
 *      fixed arrays) into a single LayoutPlan
 *   2. emit `schema.{rs,hpp,zig}` + the harness `main.*` for each language
 *   3. compile with whatever toolchains are present
 *   4. `layout` — every language must report the same sizeof/alignof as the
 *      plan; `roundtrip` — bytes encoded by the TS codec must survive a trip
 *      through the native struct unchanged
 *
 * Needs the toolchains from `flake.nix` — run inside `nix develop`. A missing
 * compiler soft-skips that language (so a bare `bun test` stays green); a
 * present compiler that fails to build is a real failure.
 */

const LONG_TIMEOUT = 180_000;
const TMP_ROOT = join(import.meta.dirname, ".tmp");
mkdirSync(TMP_ROOT, { recursive: true });
const TMP = mkdtempSync(join(TMP_ROOT, "harness-"));

const VERSION = "1.0.0";
const VERSION_MOD = "v1_0_0";
/** How many records of each type get packed into the round-trip buffer. */
const RECORD_COUNT = 3;

const TOOLCHAINS = {
	// rustc needs a C linker (cc) to produce the final binary.
	rust: {
		bins: ["cargo", "cc"],
		dir: "rust",
		build: () => $`cargo build --release`.cwd(join(TMP, "rust")).nothrow().quiet(),
		bin: join(TMP, "rust/target/release/harness"),
	},
	cpp: {
		bins: ["g++"],
		dir: "cpp",
		build: () =>
			$`g++ -std=c++17 -O1 -o harness src/main.cpp`
				.cwd(join(TMP, "cpp"))
				.nothrow()
				.quiet(),
		bin: join(TMP, "cpp/harness"),
	},
	zig: {
		bins: ["zig"],
		dir: "zig",
		build: () =>
			$`zig build-exe src/main.zig -O ReleaseSafe --name harness`
				.cwd(join(TMP, "zig"))
				.nothrow()
				.quiet(),
		bin: join(TMP, "zig/harness"),
	},
} as const;

type Lang = keyof typeof TOOLCHAINS;

const available = (Object.keys(TOOLCHAINS) as Lang[]).filter((lang) =>
	TOOLCHAINS[lang].bins.every((b) => Bun.which(b) !== null),
);

function write(relPath: string, contents: string) {
	const full = join(TMP, relPath);
	mkdirSync(dirname(full), { recursive: true });
	writeFileSync(full, contents);
}

/**
 * Schema chosen for ABI pressure, not for realism:
 *   - `Header`   trailing padding after a u8 (3 bytes)
 *   - `Vec3`     three f32 — size 12, align 4 (NOT rounded up to 16)
 *   - `Sample`   u64 first → align 8, then a nested struct and interior padding
 *   - `Transform` fixed array of a struct reference
 * Every language must agree on all of it.
 */
function buildPlan(): LayoutPlan {
	const mod = scope({
		...binary.import(),
		Header: { magic: "u32", revision: "u16", flags: "u8" },
		Vec3: { x: "f32", y: "f32", z: "f32" },
		Sample: { id: "u64", position: "Vec3", label: "u8", scale: "f32" },
		Transform: { rows: "Vec3[] == 3", weight: "f32" },
	});

	const { plan } = new SchemaAnalyzer().analyze(fromModule(mod.export()), {
		mode: "binary",
		version: VERSION,
		endian: "le",
		wordSize: "64",
	});
	return plan;
}

const plan = buildPlan();
const structNames = plan.types
	.filter((t) => t.kind === "struct")
	.map((t) => t.name);

/** Deterministic per-type fixtures — no RNG so a failure reproduces exactly. */
function fixtureFor(typeName: string, seed: number): unknown {
	const f = (n: number) => Number((seed * 1.5 + n).toFixed(2));
	switch (typeName) {
		case "Header":
			return { magic: 0xdeadbe00 + seed, revision: 100 + seed, flags: seed };
		case "Vec3":
			return { x: f(1), y: f(2), z: f(3) };
		case "Sample":
			return {
				id: 1_000_000 + seed,
				position: { x: f(1), y: f(2), z: f(3) },
				label: seed,
				scale: f(4),
			};
		case "Transform":
			return {
				rows: [
					{ x: f(1), y: f(2), z: f(3) },
					{ x: f(4), y: f(5), z: f(6) },
					{ x: f(7), y: f(8), z: f(9) },
				],
				weight: f(10),
			};
		default:
			throw new Error(`no fixture for ${typeName}`);
	}
}

/** Packs RECORD_COUNT fixtures of `typeName` into one contiguous buffer. */
function encodeRecords(typeName: string): Uint8Array {
	const type = plan.types.find((t) => t.name === typeName);
	if (!type) throw new Error(`${typeName} missing from plan`);
	const stride = type.paddedSize ?? type.size ?? 0;
	const suite = createRuntimeCodec(plan);
	const buffer = new ArrayBuffer(stride * RECORD_COUNT);
	const view = new DataView(buffer);
	for (let i = 0; i < RECORD_COUNT; i++) {
		suite.get(typeName).serialize(fixtureFor(typeName, i), view, i * stride);
	}
	return new Uint8Array(buffer);
}

describe("cross-language ABI", () => {
	beforeAll(() => {
		// One shared plan → one schema file + one harness per language.
		write("rust/src/schema.rs", exportPlan(plan, "rust", {}));
		write("cpp/src/schema.hpp", exportPlan(plan, "cpp", {}));
		write("zig/src/schema.zig", exportPlan(plan, "zig", {}));

		// Harness exporters return a Record keyed by path relative to `src/`;
		// keys starting with `../` land in the package root (Cargo.toml etc).
		const harnesses = {
			rust: exportPlan(plan, "rust:harness", {}),
			cpp: exportPlan(plan, "cpp:harness", {}),
			zig: exportPlan(plan, "zig:harness", {}),
		} as const;
		for (const [lang, files] of Object.entries(harnesses)) {
			for (const [rel, contents] of Object.entries(files)) {
				// package.json is scaffolding for a `bun run build` we don't use —
				// the build commands live in TOOLCHAINS instead.
				if (rel.endsWith("package.json")) continue;
				write(join(lang, "src", rel), contents);
			}
		}
	});

	afterAll(() => {
		rmSync(TMP, { recursive: true, force: true });
	});

	test("the plan covers every layout shape the ABI check relies on", () => {
		expect(structNames).toEqual(["Header", "Vec3", "Sample", "Transform"]);
		const byName = Object.fromEntries(plan.types.map((t) => [t.name, t]));
		// u64 first forces align 8 and makes the nested-struct offsets non-trivial.
		expect(byName.Sample?.align).toBe(8);
		// vec3-shaped struct must NOT be padded up to 16 in the plain C ABI.
		expect(byName.Vec3?.paddedSize).toBe(12);
		// u8 at the end of Header leaves trailing padding.
		expect(byName.Header?.paddedSize).toBe(8);
	});

	test(
		"native harnesses compile",
		async () => {
			if (available.length === 0) {
				console.log(
					"⏭️  no native toolchains (cargo+cc / g++ / zig) — run inside `nix develop` for the ABI check",
				);
				return;
			}
			for (const lang of available) {
				const build = await TOOLCHAINS[lang].build();
				if (build.exitCode !== 0) {
					console.error(`${lang} harness build failed:\n${build.stderr.toString()}`);
				}
				expect(build.exitCode, `${lang} harness build`).toBe(0);
			}
		},
		LONG_TIMEOUT,
	);

	test(
		"every language reports the same sizeof/alignof as the plan",
		async () => {
			if (available.length === 0) return;
			for (const lang of available) {
				const res = await $`${TOOLCHAINS[lang].bin} layout`.nothrow().quiet();
				expect(res.exitCode, `${lang} layout`).toBe(0);

				const reported = new Map<string, { size: number; align: number }>();
				for (const line of res.stdout.toString().trim().split("\n")) {
					const [ver, name, size, align] = line.split(",");
					if (ver !== VERSION_MOD) continue;
					reported.set(name!, { size: Number(size), align: Number(align) });
				}

				for (const name of structNames) {
					const planned = plan.types.find((t) => t.name === name)!;
					expect(reported.get(name), `${lang} reported ${name}`).toEqual({
						size: planned.paddedSize ?? planned.size ?? 0,
						align: planned.align ?? 1,
					});
				}
			}
		},
		LONG_TIMEOUT,
	);

	test(
		"TS-encoded bytes survive a round-trip through each native struct",
		async () => {
			if (available.length === 0) return;
			for (const name of structNames) {
				const encoded = encodeRecords(name);
				for (const lang of available) {
					const res =
						await $`${TOOLCHAINS[lang].bin} roundtrip ${VERSION_MOD} ${name} < ${encoded}`
							.nothrow()
							.quiet();
					expect(res.exitCode, `${lang} roundtrip ${name}`).toBe(0);
					expect(
						Array.from(new Uint8Array(res.stdout)),
						`${lang} roundtrip ${name} bytes`,
					).toEqual(Array.from(encoded));
				}
			}
		},
		LONG_TIMEOUT,
	);
});
