// AUTO GENERATED BY packages/schema/scripts/build_registry.ts
// DO NOT EDIT MANUALLY !
import { type } from "arktype";
import { MermaidConfig } from "./exporters/mermaid";
import { BrainfuckConfig } from "./exporters/bf";

export const ExporterConfigRegistry = type.module({
	mermaid: MermaidConfig,
	bf: BrainfuckConfig,
});
