import type {
	LayoutPlan,
	BaseConfig,
	ExporterPlugin,
	Field,
	FieldChange,
	FieldPlan,
	StructPlan,
	TypeDiff,
} from "schema-pop";
import { diffPlans, ExporterTools } from "schema-pop";

export interface CConfig
	extends Omit<BaseConfig, "fieldNaming" | "typeNaming" | "commentStyle"> {
	fieldNaming?: "snake_case";
	typeNaming?: "PascalCase";
	commentStyle?: "star";
	prefix?: string;
	/**
	 * If `true` (default), fields whose `Field.originalType` is set are
	 * emitted with the original C spelling instead of falling back to a
	 * `uint8_t name[size]` byte blob. The original spelling comes from
	 * an importer (clang_importer / treesitter_importer) which couldn't
	 * resolve the source type into a schema-pop shape — but the
	 * spelling itself is valid C, so we use it verbatim and the output
	 * compiles against the original headers.
	 *
	 * Tradeoff: such fields are no longer round-trippable through
	 * schema-pop's binary codec — the codec doesn't know the layout.
	 * Acceptable when the C output is consumed as a header bridge
	 * rather than serialised. Set to `false` to fall back to byte
	 * blobs and keep wire-format compatibility.
	 */
	useOriginalType?: boolean;
}

/**
 * Split a C type spelling into a `{type, suffix}` pair so it slots into
 * `<type> name<suffix>;` declaration form. Handles trailing array
 * dimensions (`uint8_t[64]` → `uint8_t` + `[64]`); pointer / qualifier
 * forms stay in the type slot. Function-pointer spellings would need
 * declarator-around-name placement and aren't generated by importers
 * for struct fields (they're skipped earlier as `unsupported`), so we
 * don't try to handle them here.
 */
function splitCType(spelling: string): { type: string; suffix?: string } {
	const m = spelling.match(/^(.+?)\s*((?:\[\d*\])+)\s*$/);
	if (m) return { type: m[1]!.trim(), suffix: m[2] };
	return { type: spelling.trim() };
}

const C_PRIMITIVES: Record<string, string> = {
	u8: "uint8_t",
	i8: "int8_t",
	u16: "uint16_t",
	i16: "int16_t",
	u32: "uint32_t",
	i32: "int32_t",
	u64: "uint64_t",
	i64: "int64_t",
	f32: "float",
	f64: "double",
	bool: "bool",
	boolean: "bool",
};

export function c(config: CConfig): ExporterPlugin<CConfig> {
	const cfg: CConfig = {
		fieldNaming: "snake_case",
		typeNaming: "PascalCase",
		commentStyle: "star",
		...config,
	};
	const { typeName, fieldName, indent, mapScalarField, isRichType, toSafeVersionIdentifier } =
		ExporterTools(cfg);
	return {
		name: "c",
		extension: "h",
		config: cfg,
		getFileHeader: () =>
			"#pragma once\n#include <stdint.h>\n#include <stdbool.h>\n\n",
		generate: (plan: LayoutPlan) => {
			let code = "";
			const mod = toSafeVersionIdentifier(plan.version);
			const refName = (n: string) => `${mod}_${typeName(n)}`;

			// C has no native array-of-T field declaration that fits our
			// `mapScalarField` shape (it returns just a type token). Mirror
			// cpp.ts's `{type, suffix}` pattern: arrays fall through to a
			// `uint8_t name[N]` byte blob the user can cast.
			function fieldCType(
				field: Field,
				fieldSize: number,
			): { type: string; suffix?: string } {
				const scalar = mapScalarField(field, C_PRIMITIVES, refName);
				if (scalar !== undefined) return { type: scalar };
				if (
					cfg.useOriginalType !== false &&
					field.kind === "any" &&
					typeof field.originalType === "string" &&
					field.originalType.length > 0
				) {
					return splitCType(field.originalType);
				}
				return { type: "uint8_t", suffix: `[${fieldSize}]` };
			}

			const richOpts = { allowOriginalType: cfg.useOriginalType !== false };
			for (const t of plan.types) {
				if (isRichType(t, richOpts)) {
					console.warn(
						`  ⚠ c: skipping "${t.name}" — contains rich-tier types`,
					);
					continue;
				}
				const tn = `${mod}_${typeName(t.name)}`;
				if (t.kind === "struct") {
					code += `typedef struct ${tn} {\n`;
					if (t.fields.length === 0)
						code += `${indent()}uint8_t _pad[${t.paddedSize}];\n`;
					for (const f of t.fields) {
						if (f.type.kind === "unit") continue;
						const fn = fieldName(f.name);
						if (f.bitSize && f.bitSize < 8) {
							code += `${indent()}uint8_t ${fn} : ${f.bitSize};\n`;
							if (f.paddingAfter > 0)
								code += `${indent()}uint8_t _pad_${fn}[${f.paddingAfter}];\n`;
						} else {
							const ct = fieldCType(f.type, f.size);
							code += `${indent()}${ct.type} ${fn}${ct.suffix ?? ""};\n`;
							if (f.paddingAfter > 0)
								code += `${indent()}uint8_t _pad_${fn}[${f.paddingAfter}];\n`;
						}
					}
					code += `} ${tn};\n\n`;
				} else if (t.kind === "enum") {
					const underlying =
						C_PRIMITIVES[t.underlyingType] ?? "uint8_t";
					code += `typedef ${underlying} ${tn};\n`;
					for (const v of t.variants) {
						const constName = `${tn}_${v.name}`
							.replace(/([a-z0-9])([A-Z])/g, "$1_$2")
							.replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
							.replace(/[-\s]+/g, "_")
							.toUpperCase();
						code += `#define ${constName} ((${tn})${v.value})\n`;
					}
					code += `\n`;
				} else if (t.kind === "union" || t.kind === "alias") {
					code += `typedef struct ${tn} { uint8_t _bytes[${t.paddedSize}]; } ${tn};\n\n`;
				}
			}
			return code;
		},
		generateMigration: (fromPlan: LayoutPlan, toPlan: LayoutPlan) => {
			const diff = diffPlans(fromPlan, toPlan);
			const fromMod = toSafeVersionIdentifier(fromPlan.version);
			const toMod = toSafeVersionIdentifier(toPlan.version);
			const blocks: string[] = [];
			for (const td of diff.types) {
				const code = renderCMigration(td, fromMod, toMod);
				if (code) blocks.push(code);
			}
			if (blocks.length === 0) return "";
			return `\n/* migrations: ${fromMod} -> ${toMod} */\n${blocks.join("\n")}`;
		},
	};

	function cLiteral(value: unknown): string {
		if (typeof value === "bigint") return `${value}LL`;
		if (typeof value === "boolean") return value ? "true" : "false";
		if (typeof value === "number") return `${value}`;
		if (typeof value === "string") return JSON.stringify(value);
		return "{0}";
	}

	function languageDefault(field: Field): string {
		if (field.kind === "primitive") {
			const name = (field as any).name;
			if (name === "bool" || name === "boolean") return "false";
			return "0";
		}
		return "{0}";
	}

	function emitFieldExpr(
		change: FieldChange | undefined,
		toField: FieldPlan,
	): string {
		if (change?.kind === "renamed")
			return `src->${fieldName(change.from.name)}`;
		if (change?.kind === "type-widened")
			return `src->${fieldName(change.from.name)}`;
		if (change?.kind === "added" && change.default.kind === "literal")
			return cLiteral(change.default.value);
		if (
			change?.kind === "added" &&
			change.default.kind === "language-default"
		)
			return languageDefault(toField.type);
		if (toField.migrationMeta?.defaultValue !== undefined)
			return cLiteral(toField.migrationMeta.defaultValue);
		return `src->${fieldName(toField.name)}`;
	}

	function renderCMigration(
		td: TypeDiff,
		fromMod: string,
		toMod: string,
	): string {
		if (td.kind !== "changed" && td.kind !== "renamed") return "";
		const fromType = (td as any).from;
		const toType = (td as any).to;
		const fromTypeName = `${fromMod}_${typeName(fromType.name)}`;
		const toTypeName = `${toMod}_${typeName(toType.name)}`;
		const fnName = `migrate_${typeName(toType.name)}_${fromMod}_to_${toMod}`;
		const sig = `void ${fnName}(const ${fromTypeName} *src, ${toTypeName} *dst)`;
		if (td.status === "user-supplied") {
			let s = `/* schema-pop: implement \`${sig}\` in your own .c */\n`;
			const reasons = td.fieldChanges
				.filter((c) => c.status === "user-supplied")
				.map((c) => {
					switch (c.kind) {
						case "type-narrowed":
							return `field '${c.to.name}': narrowing`;
						case "type-changed":
							return `field '${c.to.name}': structural type change`;
						case "added":
							return `field '${c.field.name}': new field with no auto default`;
						case "renamed":
							return `field '${c.to.name}': renamed AND type changed`;
						default:
							return c.kind;
					}
				});
			for (const r of reasons) s += `/*   reason: ${r} */\n`;
			s += `${sig};\n`;
			return s;
		}
		if (toType.kind === "struct") {
			const stToType = toType as StructPlan;
			const changeByToName = new Map<string, FieldChange>();
			for (const c of td.fieldChanges) {
				if (c.kind === "added") changeByToName.set(c.field.name, c);
				else if (c.kind === "renamed") changeByToName.set(c.to.name, c);
				else if (
					c.kind === "type-widened" ||
					c.kind === "type-narrowed" ||
					c.kind === "type-changed" ||
					c.kind === "reordered"
				)
					changeByToName.set(c.to.name, c);
			}
			let s = `/* status: ${td.status} */\n`;
			if (td.kind === "renamed")
				s += `/* renamed from "${td.oldName}" */\n`;
			s += `static inline ${sig} {\n`;
			for (const f of stToType.fields) {
				if (f.type.kind === "unit") continue;
				if (f.bitSize && f.bitSize < 8) continue;
				const ch = changeByToName.get(f.name);
				const expr = emitFieldExpr(ch, f);
				s += `${indent()}dst->${fieldName(f.name)} = ${expr};\n`;
			}
			s += `}\n`;
			return s;
		}
		return (
			`/* status: ${td.status} */\n` +
			`static inline ${sig} {\n` +
			`${indent()}*dst = *(const ${toTypeName} *)src;\n` +
			`}\n`
		);
	}
}
