import type {
	BaseConfig,
	ExporterPlugin,
	GpuBinding,
	GpuBindingPlan,
	LayoutPlan,
} from "@schema-pop/schema";
import { ExporterTools } from "../exporterTools";

export interface TsWebgpuConfig extends BaseConfig {
	limits?: Record<string, string>;
	codecImportPath?: string;
	bindingsImportPath?: string;
}

const STATIC_SIZES: Record<string, number> = {
	bool: 4,
	u8: 1, i8: 1,
	u16: 2, i16: 2,
	u32: 4, i32: 4, f32: 4,
	u64: 8, i64: 8, f64: 8,
	vec2f: 8, vec2i: 8, vec2u: 8, "vec2<f32>": 8, "vec2<i32>": 8, "vec2<u32>": 8,
	vec3f: 16, vec3i: 16, vec3u: 16, "vec3<f32>": 16, "vec3<i32>": 16, "vec3<u32>": 16,
	vec4f: 16, vec4i: 16, vec4u: 16, "vec4<f32>": 16, "vec4<i32>": 16, "vec4<u32>": 16,
};

function isGpuBindingPlan(t: any): t is GpuBindingPlan {
	return t.kind === "gpu-binding-layout";
}

export function tsWebgpu(
	config: TsWebgpuConfig,
): ExporterPlugin<TsWebgpuConfig> {
	const cfg = {
		fieldNaming: "original",
		typeNaming: "original",
		codecImportPath: "./Codec",
		bindingsImportPath: "./GpuBindings",
		limits: {},
		...config,
	} as const;
	const { typeName, fieldName } = ExporterTools(cfg as any);

	return {
		name: "webgpu-harness",
		extension: "ts",
		config: cfg,
		generate: (plan: LayoutPlan) => {
			const bindingPlan = plan.types.find(isGpuBindingPlan);
			if (!bindingPlan) {
				return `// No gpu-binding-layout found in schema to generate harness.`;
			}

			const limitMap = cfg.limits || {};
			const harnessName = `${typeName(bindingPlan.name)}Webgpu`;
			
			const usedDataTypes = new Set<string>();
			for (const b of bindingPlan.bindings) {
				if (b.usage !== "texture-2d" && !STATIC_SIZES[b.dataTypeName]) {
					usedDataTypes.add(b.dataTypeName);
				}
			}

			let code = `// THIS FILE IS AUTO-GENERATED BY schema-pop. DO NOT EDIT MANUALLY!\n`;
			
			if (usedDataTypes.size > 0) {
				code += `import {\n`;
				for (const type of [...usedDataTypes].sort()) {
					code += `\tSIZEOF_${type},\n`;
				}
				code += `} from "${cfg.codecImportPath}";\n`;
			}
			
			code += `import { ${typeName(bindingPlan.name).replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase()}_BINDINGS } from "${cfg.bindingsImportPath}";\n\n`;

			code += `export class ${harnessName} {\n`;
			code += `\tpublic device: GPUDevice;\n\n`;

			code += `\t// CPU Mirrors & Trackers\n`;
			for (const b of bindingPlan.bindings) {
				if (b.usage === "texture-2d") continue;
				
				const name = fieldName(b.name);
				
				// === LOGIKA ODCZYTU LIMITU / WIELKOŚCI TABLICY ===
				// Najpierw sprawdzamy exactLength lub maxLength bindowania, dopiero potem słownik limits
				const lengthVal = (b as any).exactLength !== undefined 
					? (b as any).exactLength 
					: ((b as any).maxLength !== undefined ? (b as any).maxLength : undefined);
				
				const limit = lengthVal !== undefined 
					? `${lengthVal}` 
					: (limitMap[b.dataTypeName] || "1");
				
				const sizeOfExpr = STATIC_SIZES[b.dataTypeName] !== undefined
					? `${STATIC_SIZES[b.dataTypeName]}`
					: `SIZEOF_${b.dataTypeName}`;
				
				if (b.usage.startsWith("storage") || b.usage === "uniform") {
					code += `\tprotected ${name}Cpu = new ArrayBuffer(${limit} * ${sizeOfExpr});\n`;
					code += `\tprotected ${name}View = new DataView(this.${name}Cpu);\n`;
					code += `\tprotected ${name}Count = 0;\n`;
					code += `\tprotected ${name}Dirty = false;\n\n`;
				}
			}

			code += `\t// GPU Buffers\n`;
			for (const b of bindingPlan.bindings) {
				const name = fieldName(b.name);
				code += `\tpublic ${name}Buffer!: GPUBuffer;\n`;
			}
			code += `\n`;

			code += `\t// GPU Bind Groups\n`;
			const groups = new Set<number>();
			for (const b of bindingPlan.bindings) {
				groups.add(b.group);
			}
			for (const group of [...groups].sort((a, b) => a - b)) {
				code += `\tprotected bg${group}!: GPUBindGroup;\n`;
			}
			code += `\n`;

			code += `\tconstructor(device: GPUDevice) {\n`;
			code += `\t\tthis.device = device;\n`;
			code += `\t}\n\n`;

			code += `\tprotected initBuffers(bgls: GPUBindGroupLayout[]) {\n`;
			code += `\t\tconst dev = this.device;\n`;
			code += `\t\tconst usageRW = GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST | GPUBufferUsage.COPY_SRC;\n`;
			code += `\t\tconst usageRO = GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST;\n`;
			code += `\t\tconst usageStorage = GPUBufferUsage.STORAGE;\n`;
			code += `\t\tconst usageUniform = GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST;\n\n`;

			for (const b of bindingPlan.bindings) {
				const name = fieldName(b.name);
				
				// === LOGIKA ODCZYTU LIMITU DLA ALOKACJI GPU ===
				const lengthVal = (b as any).exactLength !== undefined 
					? (b as any).exactLength 
					: ((b as any).maxLength !== undefined ? (b as any).maxLength : undefined);
				
				const limit = lengthVal !== undefined 
					? `${lengthVal}` 
					: (limitMap[b.dataTypeName] || "1");
				
				let sizeExpr = "0";
				if (b.usage !== "texture-2d") {
					sizeExpr = STATIC_SIZES[b.dataTypeName] !== undefined
						? `${limit} * ${STATIC_SIZES[b.dataTypeName]}`
						: `${limit} * SIZEOF_${b.dataTypeName}`;
				}
				
				let usageStr = "usageRW";
				if (b.usage === "storage-read") usageStr = "usageRO";
				else if (b.usage === "uniform") usageStr = "usageUniform";
				
				if (b.usage !== "texture-2d") {
					code += `\t\tthis.${name}Buffer = dev.createBuffer({\n`;
					code += `\t\t\tlabel: "${name}",\n`;
					code += `\t\t\tsize: ${sizeExpr},\n`;
					code += `\t\t\tusage: ${usageStr},\n`;
					code += `\t\t});\n`;
				}
			}
			code += `\n`;

			const byGroup = new Map<number, GpuBinding[]>();
			for (const b of bindingPlan.bindings) {
				if (!byGroup.has(b.group)) byGroup.set(b.group, []);
				byGroup.get(b.group)!.push(b);
			}

			for (const [group, bindings] of [...byGroup.entries()].sort((a, b) => a[0] - b[0])) {
				code += `\t\tthis.bg${group} = dev.createBindGroup({\n`;
				code += `\t\t\tlayout: bgls[${group}],\n`;
				code += `\t\t\tentries: [\n`;
				for (const b of bindings.sort((a, bb) => a.binding - bb.binding)) {
					const name = fieldName(b.name);
					if (b.usage === "texture-2d") {
						code += `\t\t\t\t{ binding: ${b.binding}, resource: /* TODO: Bind texture view */ },\n`;
					} else {
						code += `\t\t\t\t{ binding: ${b.binding}, resource: { buffer: this.${name}Buffer } },\n`;
					}
				}
				code += `\t\t\t],\n`;
				code += `\t\t});\n`;
			}

			code += `\t}\n`;
			code += `}\n`;

			return code;
		},
	};
}