import type {
	BaseConfig,
	ExporterPlugin,
	GpuBinding,
	GpuBindingPlan,
	LayoutPlan,
} from "@schema-pop/schema";
import { ExporterTools } from "../exporterTools";

export interface TsWebgpuConfig extends BaseConfig {
	/**
	 * Słownik mapujący typy danych na stałe określające ich maksymalne limity.
	 * np. { "Particle": "ENGINE.MAX_PARTICLES", "Constraint": "ENGINE.MAX_CONSTRAINTS" }
	 */
	limits?: Record<string, string>;
	/**
	 * Nazwa pliku lub ścieżka do Codeca (potrzebne do SIZEOF_...)
	 * Domyślnie "./Codec"
	 */
	codecImportPath?: string;
	/**
	 * Nazwa pliku lub ścieżka do GpuBindings
	 * Domyślnie "./GpuBindings"
	 */
	bindingsImportPath?: string;
}

// Słownik znanych typów wbudowanych WebGPU oraz ich rozmiarów w bajtach.
// Pomaga uniknąć próby importowania SIZEOF_i32 z Codeca.
const STATIC_SIZES: Record<string, number> = {
	bool: 4, // WGSL host-shareable bool reprezentujemy w buforach jako u32 (4 bajty)
	u8: 1,
	i8: 1,
	u16: 2,
	i16: 2,
	u32: 4,
	i32: 4,
	f32: 4,
	f64: 8,
	u64: 8,
	i64: 8,
	// Standardowe typy wektorowe WebGPU (z uwzględnieniem wyrównania std140/std430)
	vec2f: 8,
	vec2i: 8,
	vec2u: 8,
	"vec2<f32>": 8,
	"vec2<i32>": 8,
	"vec2<u32>": 8,
	vec3f: 16, // vec3 w WGSL zajmuje 16 bajtów ze względu na wyrównanie do 16
	vec3i: 16,
	vec3u: 16,
	"vec3<f32>": 16,
	"vec3<i32>": 16,
	"vec3<u32>": 16,
	vec4f: 16,
	vec4i: 16,
	vec4u: 16,
	"vec4<f32>": 16,
	"vec4<i32>": 16,
	"vec4<u32>": 16,
};

function isGpuBindingPlan(t: any): t is GpuBindingPlan {
	return t.kind === "gpu-binding-layout";
}

export function tsWebgpu(
	config: TsWebgpuConfig,
): ExporterPlugin<TsWebgpuConfig> {
	const cfg = {
		fieldNaming: "original",
		typeNaming: "original",
		codecImportPath: "./Codec",
		bindingsImportPath: "./GpuBindings",
		limits: {},
		...config,
	} as const;
	const { typeName, fieldName } = ExporterTools(cfg as any);

	return {
		name: "webgpu-harness",
		extension: "ts",
		config: cfg,
		generate: (plan: LayoutPlan) => {
			const bindingPlan = plan.types.find(isGpuBindingPlan);
			if (!bindingPlan) {
				return `// No gpu-binding-layout found in schema to generate harness.`;
			}

			const limitMap = cfg.limits || {};
			const harnessName = `${typeName(bindingPlan.name)}Webgpu`;
			
			// Pobieramy typy danych z pominięciem typów wbudowanych (STATIC_SIZES)
			const usedDataTypes = new Set<string>();
			for (const b of bindingPlan.bindings) {
				if (b.usage !== "texture-2d" && !STATIC_SIZES[b.dataTypeName]) {
					usedDataTypes.add(b.dataTypeName);
				}
			}

			// 1. Generowanie nagłówka i importów
			let code = `// THIS FILE IS AUTO-GENERATED BY schema-pop. DO NOT EDIT MANUALLY!\n`;
			
			// Importujemy SIZEOF tylko dla struktur użytkownika
			if (usedDataTypes.size > 0) {
				code += `import {\n`;
				for (const type of [...usedDataTypes].sort()) {
					code += `\tSIZEOF_${type},\n`;
				}
				code += `} from "${cfg.codecImportPath}";\n`;
			}
			
			code += `import { ${typeName(bindingPlan.name).replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase()}_BINDINGS } from "${cfg.bindingsImportPath}";\n\n`;

			// 2. Klasa bazowa
			code += `export class ${harnessName} {\n`;
			code += `\tprotected device: GPUDevice;\n\n`;

			// 3. Generowanie deklaracji pól CPU mirrorów i buforów GPU
			code += `\t// CPU Mirrors & Trackers\n`;
			for (const b of bindingPlan.bindings) {
				if (b.usage === "texture-2d") continue;
				
				const name = fieldName(b.name);
				const limit = limitMap[b.dataTypeName] || "1";
				
				// Jeżeli to typ wbudowany, używamy wartości numerycznej, inaczej importowanej stałej SIZEOF_...
				const sizeOfExpr = STATIC_SIZES[b.dataTypeName] !== undefined
					? `${STATIC_SIZES[b.dataTypeName]}`
					: `SIZEOF_${b.dataTypeName}`;
				
				if (b.usage.startsWith("storage") || b.usage === "uniform") {
					code += `\tprotected ${name}Cpu = new ArrayBuffer(${limit} * ${sizeOfExpr});\n`;
					code += `\tprotected ${name}View = new DataView(this.${name}Cpu);\n`;
					code += `\tprotected ${name}Count = 0;\n`;
					code += `\tprotected ${name}Dirty = false;\n\n`;
				}
			}

			code += `\t// GPU Buffers\n`;
			for (const b of bindingPlan.bindings) {
				const name = fieldName(b.name);
				code += `\tprotected ${name}Buffer!: GPUBuffer;\n`;
			}
			code += `\n`;

			code += `\t// GPU Bind Groups\n`;
			const groups = new Set<number>();
			for (const b of bindingPlan.bindings) {
				groups.add(b.group);
			}
			for (const group of [...groups].sort((a, b) => a - b)) {
				code += `\tprotected bg${group}!: GPUBindGroup;\n`;
			}
			code += `\n`;

			// 4. Konstruktor
			code += `\tconstructor(device: GPUDevice) {\n`;
			code += `\t\tthis.device = device;\n`;
			code += `\t}\n\n`;

			// 5. Metoda inicjalizacyjna (initBuffers)
			code += `\tprotected initBuffers(bgls: GPUBindGroupLayout[]) {\n`;
			code += `\t\tconst dev = this.device;\n`;
			code += `\t\tconst usageRW = GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST | GPUBufferUsage.COPY_SRC;\n`;
			code += `\t\tconst usageRO = GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST;\n`;
			code += `\t\tconst usageStorage = GPUBufferUsage.STORAGE;\n`;
			code += `\t\tconst usageUniform = GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST;\n\n`;

			// Alokacja każdego bufora na podstawie jego usage
			for (const b of bindingPlan.bindings) {
				const name = fieldName(b.name);
				const limit = limitMap[b.dataTypeName] || "1";
				
				let sizeExpr = "0";
				if (b.usage !== "texture-2d") {
					sizeExpr = STATIC_SIZES[b.dataTypeName] !== undefined
						? `${limit} * ${STATIC_SIZES[b.dataTypeName]}`
						: `${limit} * SIZEOF_${b.dataTypeName}`;
				}
				
				let usageStr = "usageRW";
				if (b.usage === "storage-read") usageStr = "usageRO";
				else if (b.usage === "uniform") usageStr = "usageUniform";
				
				if (b.usage !== "texture-2d") {
					code += `\t\tthis.${name}Buffer = dev.createBuffer({\n`;
					code += `\t\t\tlabel: "${name}",\n`;
					code += `\t\t\tsize: ${sizeExpr},\n`;
					code += `\t\t\tusage: ${usageStr},\n`;
					code += `\t\t});\n`;
				}
			}
			code += `\n`;

			// 6. Alokacja Bind Group
			const byGroup = new Map<number, GpuBinding[]>();
			for (const b of bindingPlan.bindings) {
				if (!byGroup.has(b.group)) byGroup.set(b.group, []);
				byGroup.get(b.group)!.push(b);
			}

			for (const [group, bindings] of [...byGroup.entries()].sort((a, b) => a[0] - b[0])) {
				code += `\t\tthis.bg${group} = dev.createBindGroup({\n`;
				code += `\t\t\tlayout: bgls[${group}],\n`;
				code += `\t\t\tentries: [\n`;
				for (const b of bindings.sort((a, bb) => a.binding - bb.binding)) {
					const name = fieldName(b.name);
					if (b.usage === "texture-2d") {
						code += `\t\t\t\t{ binding: ${b.binding}, resource: /* TODO: Bind texture view */ },\n`;
					} else {
						code += `\t\t\t\t{ binding: ${b.binding}, resource: { buffer: this.${name}Buffer } },\n`;
					}
				}
				code += `\t\t\t],\n`;
				code += `\t\t});\n`;
			}

			code += `\t}\n`;
			code += `}\n`;

			return code;
		},
	};
}