import type {
	BaseConfig,
	ExporterPlugin,
	LayoutPlan,
} from "@schema-pop/schema";
import { ExporterTools } from "../exporterTools";

export interface ZigMatcherConfig
	extends Omit<BaseConfig, "fieldNaming" | "typeNaming" | "commentStyle"> {
	fieldNaming?: "snake_case";
	typeNaming?: "PascalCase";
	/** Path to the base schema generated by the zig exporter */
	schemaImportPath?: string;
}

export function zigMatcher(
	config: ZigMatcherConfig,
): ExporterPlugin<ZigMatcherConfig> {
	const cfg: ZigMatcherConfig = {
		fieldNaming: "snake_case",
		typeNaming: "PascalCase",
		schemaImportPath: "schema.zig",
		...config,
	};

	const { typeName, fieldName, toSafeVersionIdentifier, indent } =
		ExporterTools(cfg);

	return {
		name: "zig-matcher",
		extension: "matcher.zig",
		config: cfg,
		getFileHeader: () => {
			return (
				`const std = @import("std");\n` +
				`const schema = @import("${cfg.schemaImportPath}");\n\n` +
				`// Context provided by Bun FFI to validate memory bounds\n` +
				`pub const ScanContext = extern struct {\n` +
				`\tmin_ptr: usize,\n` +
				`\tmax_ptr: usize,\n\n` +
				`\tpub inline fn isValidPtr(self: ScanContext, ptr: usize) bool {\n` +
				`\t\tif (ptr == 0) return true; // NULL is usually valid\n` +
				`\t\treturn ptr >= self.min_ptr and ptr <= self.max_ptr;\n` +
				`\t}\n` +
				`};\n\n`
			);
		},
		generate: (plan: LayoutPlan) => {
			let code = "";
			const versionNs = toSafeVersionIdentifier(plan.version);

			for (const t of plan.types) {
				if (t.kind !== "struct") continue;

				const tn = typeName(t.name);
				const structPath = `schema.${versionNs}.${tn}`;

				let checks: string[] = [];

				// 1. Basic alignment check
				checks.push(`if (addr % @alignOf(${structPath}) != 0) return false;`);
				checks.push(`const s: *const ${structPath} = @ptrFromInt(addr);`);

				for (const f of t.fields) {
					if (f.type.kind === "unit") continue;
					const fn = fieldName(f.name);

					// 2. Pointer heuristic
					if (f.type.kind === "reference" && f.type.indirection === "pointer") {
						checks.push(
							`if (!ctx.isValidPtr(@intFromPtr(s.${fn}))) return false;`,
						);

						// Double-linked list heuristic (e.g. pxNext / pxPrevious)
						if (fn.toLowerCase().includes("next")) {
							checks.push(
								`// List consistency heuristic: ptr->next should be a valid memory region`,
								`if (@intFromPtr(s.${fn}) != 0) {`,
								`\t// Note: strict check like 'ptr->next->prev == ptr' requires safe memory reading`,
								`\t// avoiding dereference here to prevent segfaults if pointer is garbage.`,
								`}`,
							);
						}
					}

					// 3. Enum bounds heuristic
					if (f.type.kind === "reference") {
						const refPlan = plan.types.find((x) => x.name === f.type.kind);
						if (refPlan && refPlan.kind === "enum") {
							const maxVal = Math.max(...refPlan.variants.map((v) => v.value));
							checks.push(
								`if (@intFromEnum(s.${fn}) > ${maxVal}) return false;`,
							);
						}
					}

					// 4. Zero padding heuristic
					// Matches the padding generation logic from your zig exporter
					if (f.paddingAfter > 0) {
						const padName =
							f.bitSize && f.bitSize < 8 ? `_pad_${f.offset}` : `_pad_${fn}`;
						checks.push(`for (s.${padName}) |b| { if (b != 0) return false; }`);
					}
				}

				// Generate the validation function
				code += `pub fn isValid_${tn}(addr: usize, ctx: ScanContext) bool {\n`;
				for (const check of checks) {
					code += `${indent()}${check}\n`;
				}
				code += `${indent()}return true;\n`;
				code += `}\n\n`;

				// Generate the exported FFI scanner function
				code += `// Exported for Bun FFI\n`;
				code += `export fn scanFor_${versionNs}_${tn}(start: usize, end: usize, min_ptr: usize, max_ptr: usize) usize {\n`;
				code += `${indent()}const ctx = ScanContext{ .min_ptr = min_ptr, .max_ptr = max_ptr };\n`;
				code += `${indent()}var addr = start;\n`;
				code += `${indent()}const align_val = @alignOf(${structPath});\n`;
				code += `${indent()}// align start address\n`;
				code += `${indent()}addr = (addr + (align_val - 1)) & ~(align_val - 1);\n\n`;
				code += `${indent()}while (addr + @sizeOf(${structPath}) <= end) : (addr += align_val) {\n`;
				code += `${indent()}${indent()}if (isValid_${tn}(addr, ctx)) return addr;\n`;
				code += `${indent()}}\n`;
				code += `${indent()}return 0;\n`;
				code += `}\n\n`;
			}

			return code;
		},
		wrapVersion: (version, code) =>
			// We don't need to wrap the whole file in a namespace struct because
			// exported FFI functions need to be top-level anyway.
			// We already embed `versionNs` in the exported function names.
			`// Scanner for version: ${version}\n${code}`,
	};
}
