import type {
	RustField,
	RustItem,
	RustModuleIR,
	RustType,
} from "./ir";

/**
 * IR → arktype scope source. The output file is meant to be hand-readable
 * and to plug into a normal schema-pop pipeline as `versions[].source`.
 *
 * Conventions:
 *  - Primitives are emitted as the same string ("u32", etc.) — schema-pop's
 *    `binary` scope already exports those names.
 *  - References are emitted by name; cross-references inside one scope are
 *    fine because arktype resolves them lazily.
 *  - Doc-comments are converted to `.describe(...)` chains via the
 *    `describe` helper from schema-pop core.
 *  - Items with `repr(uN)` on an all-unit enum are emitted as a string
 *    literal union (closest equivalent in our analyzer).
 */

export type EmitOptions = {
	scopeName?: string; // default: "$"
	header?: string; // raw text prepended to file (e.g., a banner)
};

export function emitArktypeScope(
	ir: RustModuleIR,
	opts: EmitOptions = {},
): string {
	const scopeName = opts.scopeName ?? "$";
	const header = opts.header ?? defaultHeader(ir.source);

	const aliases: string[] = [];
	for (const item of ir.items) aliases.push(emitItem(item));

	const skipped =
		ir.skipped.length > 0
			? `\n// Skipped (unsupported by tree-sitter MVP):\n${ir.skipped
					.map((s) => `//   ${s.name} — ${s.reason}`)
					.join("\n")}\n`
			: "";

	return `${header}
import { scope } from "schema-pop";
import { binary } from "schema-pop";

export const ${scopeName} = scope({
\t...binary.import(),
${aliases.map((a) => indent(a, 1)).join(",\n")}${aliases.length ? "," : ""}
});
${skipped}`;
}

function defaultHeader(sourcePath: string): string {
	return `// AUTO-GENERATED by @schema-pop/treesitter-importer
// Source: ${sourcePath}
// Edit the .rs file and re-run the importer; do not hand-edit this file.
`;
}

function emitItem(item: RustItem): string {
	if (item.kind === "struct") {
		const lines = item.fields
			.filter((f) => emittableField(f))
			.map((f) => emitField(f));
		return `${quoteTypeName(item.name)}: {\n${lines.join(",\n")}\n}`;
	}
	if (item.kind === "enum") {
		// All unit variants → string literal union; carry tag size via
		// description if repr is present.
		const allUnit = item.variants.every((v) => v.kind === "unit");
		if (allUnit) {
			const lits = item.variants.map((v) => `'${v.name}'`).join(" | ");
			return `${quoteTypeName(item.name)}: ${JSON.stringify(lits)}`;
		}
		// Discriminated tagged union: emit each variant as a struct ref then
		// a union of those refs. For MVP keep it simple: emit per-variant
		// inline structs and join them.
		const variantTypes: string[] = [];
		const sub: string[] = [];
		for (let i = 0; i < item.variants.length; i++) {
			const v = item.variants[i]!;
			const tagLit = String(i);
			if (v.kind === "unit") {
				const variantTypeName = `${item.name}_${v.name}`;
				sub.push(
					`${quoteTypeName(variantTypeName)}: { tag: '${tagLit}' }`,
				);
				variantTypes.push(variantTypeName);
			} else if (v.kind === "tuple") {
				// One-arg tuple variant: `Variant(T)` → struct { tag, value }.
				if (v.types.length === 1) {
					const variantTypeName = `${item.name}_${v.name}`;
					sub.push(
						`${quoteTypeName(variantTypeName)}: { tag: '${tagLit}', value: ${emitTypeAsString(v.types[0]!)} }`,
					);
					variantTypes.push(variantTypeName);
				} else {
					sub.push(
						`// (skipped tuple variant ${item.name}::${v.name} with ${v.types.length} args)`,
					);
				}
			} else if (v.kind === "struct") {
				const variantTypeName = `${item.name}_${v.name}`;
				const lines = v.fields.map(
					(f) => `\t\t${quoteFieldName(f.name)}: ${emitTypeAsString(f.type)}`,
				);
				sub.push(
					`${quoteTypeName(variantTypeName)}: { tag: '${tagLit}',\n${lines.join(",\n")}\n}`,
				);
				variantTypes.push(variantTypeName);
			}
		}
		const unionExpr = variantTypes.join(" | ");
		const all = [
			...sub,
			`${quoteTypeName(item.name)}: ${JSON.stringify(unionExpr)}`,
		];
		return all.join(",\n");
	}
	// alias
	return `${quoteTypeName(item.name)}: ${emitTypeAsString(item.type)}`;
}

function emittableField(f: RustField): boolean {
	return f.type.kind !== "unsupported";
}

function emitField(f: RustField): string {
	// Option<T> at field level → "name?": "T" (arktype optional-key form).
	if (f.type.kind === "option") {
		const innerExpr = emitTypeAsString(f.type.inner);
		const key = f.name + "?";
		return `\t${JSON.stringify(key)}: ${innerExpr}`;
	}
	return `\t${quoteFieldName(f.name)}: ${emitTypeAsString(f.type)}`;
}

function emitTypeAsString(t: RustType): string {
	switch (t.kind) {
		case "primitive":
			return JSON.stringify(t.name);
		case "ref":
			return JSON.stringify(t.name);
		case "string":
			return JSON.stringify("string");
		case "array": {
			const inner = innerStringForArktype(t.item);
			return JSON.stringify(`${inner}[] == ${t.len}`);
		}
		case "option": {
			const inner = innerStringForArktype(t.inner);
			return JSON.stringify(`${inner} | undefined`);
		}
		case "vec": {
			const inner = innerStringForArktype(t.item);
			return JSON.stringify(`${inner}[]`);
		}
		case "unsupported":
			return `/* unsupported: ${t.raw} */ "any"`;
	}
}

function innerStringForArktype(t: RustType): string {
	// For nested types inside a string-form arktype expression we strip the
	// outer quotes. Keep it conservative: only primitive/ref/string forms.
	if (t.kind === "primitive") return t.name;
	if (t.kind === "ref") return t.name;
	if (t.kind === "string") return "string";
	if (t.kind === "array") {
		return `${innerStringForArktype(t.item)}[] == ${t.len}`;
	}
	if (t.kind === "vec") {
		return `${innerStringForArktype(t.item)}[]`;
	}
	if (t.kind === "option") {
		return `${innerStringForArktype(t.inner)} | undefined`;
	}
	return "any";
}

function quoteFieldName(name: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) return name;
	return JSON.stringify(name);
}

function quoteTypeName(name: string): string {
	return quoteFieldName(name);
}

function indent(text: string, n: number): string {
	const pad = "\t".repeat(n);
	return text
		.split("\n")
		.map((l) => (l.length ? pad + l : l))
		.join("\n");
}
