import type {
	RustField,
	RustItem,
	RustModuleIR,
	RustType,
} from "./ir";

/**
 * IR → arktype scope source. The output file is meant to be hand-readable
 * and to plug into a normal schema-pop pipeline as `versions[].source`.
 *
 * Conventions:
 *  - Primitives are emitted as the same string ("u32", etc.) — schema-pop's
 *    `binary` scope already exports those names.
 *  - References are emitted by name; cross-references inside one scope are
 *    fine because arktype resolves them lazily.
 *  - Doc-comments are converted to `.describe(...)` chains via the
 *    `describe` helper from schema-pop core.
 *  - Items with `repr(uN)` on an all-unit enum are emitted as a string
 *    literal union (closest equivalent in our analyzer).
 */

export type EmitOptions = {
	scopeName?: string; // default: "$"
	header?: string; // raw text prepended to file (e.g., a banner)
};

export function emitArktypeScope(
	ir: RustModuleIR,
	opts: EmitOptions = {},
): string {
	const scopeName = opts.scopeName ?? "$";
	const header = opts.header ?? defaultHeader(ir.source);

	const typeItems = ir.items.filter((i) => i.kind !== "function");
	const fnItems = ir.items.filter(
		(i): i is Extract<RustItem, { kind: "function" }> => i.kind === "function",
	);

	const aliases: string[] = [];
	for (const item of typeItems) aliases.push(emitItem(item));

	const skipped =
		ir.skipped.length > 0
			? `\n// Skipped (unsupported by tree-sitter MVP):\n${ir.skipped
					.map((s) => `//   ${s.name} — ${s.reason}`)
					.join("\n")}\n`
			: "";

	const fnsBlock = fnItems.length ? emitFunctions(fnItems) : "";

	return `${header}
import { scope } from "schema-pop";
import { binary } from "schema-pop";${fnItems.length ? `\nimport type { FunctionPlan } from "schema-pop";` : ""}

export const ${scopeName} = scope({
\t...binary.import(),
${aliases.map((a) => indent(a, 1)).join(",\n")}${aliases.length ? "," : ""}
});
${fnsBlock}${skipped}`;
}

/**
 * Emit a `export const functions: FunctionPlan[] = [...]` block. Each entry
 * is a plain object literal compatible with schema-pop's `FunctionPlan` TS
 * type. Field types are encoded directly as IR primitives → schema-pop
 * `Field` shapes (no string-form arktype expressions, since functions
 * bypass the arktype scope entirely).
 */
function emitFunctions(
	fns: Extract<RustItem, { kind: "function" }>[],
): string {
	const entries = fns.map((fn) => {
		const argEntries = fn.args.map(
			(a) =>
				`\t\t\t{ ${a.name ? `name: ${JSON.stringify(a.name)}, ` : ""}type: ${emitFieldLiteral(a.type)} }`,
		);
		const ret = emitFieldLiteral(fn.returnType);
		const docPart = fn.doc
			? `\n\t\tdescription: ${JSON.stringify(fn.doc)},`
			: "";
		const abiPart = fn.abi ? `\n\t\tabi: ${JSON.stringify(fn.abi)},` : "";
		return `\t{
\t\tname: ${JSON.stringify(fn.name)},
\t\tsymbol: ${JSON.stringify(fn.name)},${abiPart}${docPart}
\t\treturnType: ${ret},
\t\targs: [${argEntries.length ? `\n${argEntries.join(",\n")}\n\t\t` : ""}],
\t}`;
	});
	return `\nexport const functions: FunctionPlan[] = [\n${entries.join(",\n")},\n];\n`;
}

/**
 * Emit a IR `RustType` as a literal `Field` object compatible with
 * schema-pop's `Field` union. Used inside function argument / return
 * types where there's no string-form arktype available.
 */
function emitFieldLiteral(t: RustType): string {
	switch (t.kind) {
		case "primitive":
			return `{ kind: "primitive", name: ${JSON.stringify(t.name)}, size: ${primitiveSize(t.name)}, align: ${primitiveAlign(t.name)}, paddedSize: ${primitiveSize(t.name)}, popKind: "binary" }`;
		case "ref":
			return `{ kind: "reference", name: ${JSON.stringify(t.name)}, indirection: "inline", isForward: false, size: 0, align: 1, paddedSize: 0 }`;
		case "string":
			return `{ kind: "string" }`;
		case "array": {
			return `{ kind: "array", item: ${emitFieldLiteral(t.item)}, exactLength: ${t.len}, size: 0, align: 1, paddedSize: 0 }`;
		}
		case "vec": {
			return `{ kind: "array", item: ${emitFieldLiteral(t.item)}, size: 0, align: 1, paddedSize: 0 }`;
		}
		case "option": {
			return `{ kind: "optional", inner: ${emitFieldLiteral(t.inner)} }`;
		}
		case "unsupported":
			// `()` (Rust unit) and `void` (C) → encode as `unit` field.
			if (t.raw === "()" || t.raw === "void") {
				return `{ kind: "unit" }`;
			}
			return `{ kind: "any" /* unsupported: ${escapeJsBlock(t.raw)} */ }`;
	}
}

function escapeJsBlock(s: string): string {
	return s.replace(/\*\//g, "*\\/").replace(/\n/g, " ");
}

function primitiveSize(name: string): number {
	const m: Record<string, number> = {
		u8: 1, i8: 1, bool: 1,
		u16: 2, i16: 2,
		u32: 4, i32: 4, f32: 4,
		u64: 8, i64: 8, f64: 8,
		u128: 16, i128: 16,
	};
	return m[name] ?? 0;
}
function primitiveAlign(name: string): number {
	return primitiveSize(name) || 1;
}

function defaultHeader(sourcePath: string): string {
	return `// AUTO-GENERATED by @schema-pop/treesitter-importer
// Source: ${sourcePath}
// Edit the .rs file and re-run the importer; do not hand-edit this file.
`;
}

function emitItem(item: RustItem): string {
	if (item.kind === "struct") {
		const lines = item.fields
			.filter((f) => emittableField(f))
			.map((f) => emitField(f));
		return `${quoteTypeName(item.name)}: {\n${lines.join(",\n")}\n}`;
	}
	if (item.kind === "enum") {
		// All unit variants → string literal union; carry tag size via
		// description if repr is present.
		const allUnit = item.variants.every((v) => v.kind === "unit");
		if (allUnit) {
			const lits = item.variants.map((v) => `'${v.name}'`).join(" | ");
			return `${quoteTypeName(item.name)}: ${JSON.stringify(lits)}`;
		}
		// Discriminated tagged union: emit each variant as a struct ref then
		// a union of those refs. For MVP keep it simple: emit per-variant
		// inline structs and join them.
		const variantTypes: string[] = [];
		const sub: string[] = [];
		for (let i = 0; i < item.variants.length; i++) {
			const v = item.variants[i]!;
			const tagLit = String(i);
			if (v.kind === "unit") {
				const variantTypeName = `${item.name}_${v.name}`;
				sub.push(
					`${quoteTypeName(variantTypeName)}: { tag: '${tagLit}' }`,
				);
				variantTypes.push(variantTypeName);
			} else if (v.kind === "tuple") {
				// One-arg tuple variant: `Variant(T)` → struct { tag, value }.
				if (v.types.length === 1) {
					const variantTypeName = `${item.name}_${v.name}`;
					sub.push(
						`${quoteTypeName(variantTypeName)}: { tag: '${tagLit}', value: ${emitTypeAsString(v.types[0]!)} }`,
					);
					variantTypes.push(variantTypeName);
				} else {
					sub.push(
						`// (skipped tuple variant ${item.name}::${v.name} with ${v.types.length} args)`,
					);
				}
			} else if (v.kind === "struct") {
				const variantTypeName = `${item.name}_${v.name}`;
				const lines = v.fields.map(
					(f) => `\t\t${quoteFieldName(f.name)}: ${emitTypeAsString(f.type)}`,
				);
				sub.push(
					`${quoteTypeName(variantTypeName)}: { tag: '${tagLit}',\n${lines.join(",\n")}\n}`,
				);
				variantTypes.push(variantTypeName);
			}
		}
		const unionExpr = variantTypes.join(" | ");
		const all = [
			...sub,
			`${quoteTypeName(item.name)}: ${JSON.stringify(unionExpr)}`,
		];
		return all.join(",\n");
	}
	if (item.kind === "alias") {
		return `${quoteTypeName(item.name)}: ${emitTypeAsString(item.type)}`;
	}
	// function items are emitted via emitFunctions, not inside the scope.
	return "";
}

function emittableField(f: RustField): boolean {
	return f.type.kind !== "unsupported";
}

function emitField(f: RustField): string {
	// Option<T> at field level → "name?": "T" (arktype optional-key form).
	if (f.type.kind === "option") {
		const innerExpr = emitTypeAsString(f.type.inner);
		const key = f.name + "?";
		return `\t${JSON.stringify(key)}: ${innerExpr}`;
	}
	return `\t${quoteFieldName(f.name)}: ${emitTypeAsString(f.type)}`;
}

function emitTypeAsString(t: RustType): string {
	switch (t.kind) {
		case "primitive":
			return JSON.stringify(t.name);
		case "ref":
			return JSON.stringify(t.name);
		case "string":
			return JSON.stringify("string");
		case "array": {
			const inner = innerStringForArktype(t.item);
			return JSON.stringify(`${inner}[] == ${t.len}`);
		}
		case "option": {
			const inner = innerStringForArktype(t.inner);
			return JSON.stringify(`${inner} | undefined`);
		}
		case "vec": {
			const inner = innerStringForArktype(t.item);
			return JSON.stringify(`${inner}[]`);
		}
		case "unsupported":
			return `/* unsupported: ${t.raw} */ "any"`;
	}
}

function innerStringForArktype(t: RustType): string {
	// For nested types inside a string-form arktype expression we strip the
	// outer quotes. Keep it conservative: only primitive/ref/string forms.
	if (t.kind === "primitive") return t.name;
	if (t.kind === "ref") return t.name;
	if (t.kind === "string") return "string";
	if (t.kind === "array") {
		return `${innerStringForArktype(t.item)}[] == ${t.len}`;
	}
	if (t.kind === "vec") {
		return `${innerStringForArktype(t.item)}[]`;
	}
	if (t.kind === "option") {
		return `${innerStringForArktype(t.inner)} | undefined`;
	}
	return "any";
}

function quoteFieldName(name: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) return name;
	return JSON.stringify(name);
}

function quoteTypeName(name: string): string {
	return quoteFieldName(name);
}

function indent(text: string, n: number): string {
	const pad = "\t".repeat(n);
	return text
		.split("\n")
		.map((l) => (l.length ? pad + l : l))
		.join("\n");
}
